// This file was automatically generated by EbnfStudio; don't modify it!
#include "ExpParser.h"
using namespace Exp;

static inline bool FIRST_syntax(int tt) {
	return tt == Tok_SCHEMA;
}

static inline bool FIRST_schema_decl(int tt) {
	return tt == Tok_SCHEMA;
}

static inline bool FIRST_schema_body(int tt) {
	switch(tt){
	case Tok_CONSTANT:
	case Tok_ENTITY:
	case Tok_FUNCTION:
	case Tok_PROCEDURE:
	case Tok_REFERENCE:
	case Tok_RULE:
	case Tok_SUBTYPE_CONSTRAINT:
	case Tok_TYPE:
	case Tok_USE:
		return true;
	default: return false;
	}
}

static inline bool FIRST_interface_specification(int tt) {
	return tt == Tok_REFERENCE || tt == Tok_USE;
}

static inline bool FIRST_reference_clause(int tt) {
	return tt == Tok_REFERENCE;
}

static inline bool FIRST_use_clause(int tt) {
	return tt == Tok_USE;
}

static inline bool FIRST_resource_or_rename(int tt) {
	return tt == Tok_ident;
}

static inline bool FIRST_named_type_or_rename(int tt) {
	return tt == Tok_ident;
}

static inline bool FIRST_declaration(int tt) {
	return tt == Tok_ENTITY || tt == Tok_FUNCTION || tt == Tok_PROCEDURE || tt == Tok_SUBTYPE_CONSTRAINT || tt == Tok_TYPE;
}

static inline bool FIRST_constant_decl(int tt) {
	return tt == Tok_CONSTANT;
}

static inline bool FIRST_constant_body(int tt) {
	return tt == Tok_ident;
}

static inline bool FIRST_entity_decl(int tt) {
	return tt == Tok_ENTITY;
}

static inline bool FIRST_entity_head(int tt) {
	return tt == Tok_ENTITY;
}

static inline bool FIRST_subsuper(int tt) {
	return tt == Tok_ABSTRACT || tt == Tok_SUBTYPE || tt == Tok_SUPERTYPE;
}

static inline bool FIRST_supertype_constraint(int tt) {
	return tt == Tok_ABSTRACT || tt == Tok_SUPERTYPE;
}

static inline bool FIRST_subtype_constraint(int tt) {
	return tt == Tok_OF;
}

static inline bool FIRST_subtype_declaration(int tt) {
	return tt == Tok_SUBTYPE;
}

static inline bool FIRST_supertype_expression(int tt) {
	return tt == Tok_Lpar || tt == Tok_ONEOF || tt == Tok_ident;
}

static inline bool FIRST_supertype_factor(int tt) {
	return tt == Tok_Lpar || tt == Tok_ONEOF || tt == Tok_ident;
}

static inline bool FIRST_supertype_term(int tt) {
	return tt == Tok_Lpar || tt == Tok_ONEOF || tt == Tok_ident;
}

static inline bool FIRST_one_of(int tt) {
	return tt == Tok_ONEOF;
}

static inline bool FIRST_entity_body(int tt) {
	switch(tt){
	case Tok_DERIVE:
	case Tok_INVERSE:
	case Tok_SELF:
	case Tok_UNIQUE:
	case Tok_WHERE:
	case Tok_ident:
		return true;
	default: return false;
	}
}

static inline bool FIRST_explicit_attr(int tt) {
	return tt == Tok_SELF || tt == Tok_ident;
}

static inline bool FIRST_attribute_decl(int tt) {
	return tt == Tok_SELF || tt == Tok_ident;
}

static inline bool FIRST_redeclared_attribute(int tt) {
	return tt == Tok_SELF;
}

static inline bool FIRST_qualified_attribute(int tt) {
	return tt == Tok_SELF;
}

static inline bool FIRST_derive_clause(int tt) {
	return tt == Tok_DERIVE;
}

static inline bool FIRST_derived_attr(int tt) {
	return tt == Tok_SELF || tt == Tok_ident;
}

static inline bool FIRST_inverse_clause(int tt) {
	return tt == Tok_INVERSE;
}

static inline bool FIRST_inverse_attr(int tt) {
	return tt == Tok_SELF || tt == Tok_ident;
}

static inline bool FIRST_unique_clause(int tt) {
	return tt == Tok_UNIQUE;
}

static inline bool FIRST_unique_rule(int tt) {
	return tt == Tok_SELF || tt == Tok_ident;
}

static inline bool FIRST_referenced_attribute(int tt) {
	return tt == Tok_SELF || tt == Tok_ident;
}

static inline bool FIRST_type_decl(int tt) {
	return tt == Tok_TYPE;
}

static inline bool FIRST_underlying_type(int tt) {
	switch(tt){
	case Tok_ARRAY:
	case Tok_BAG:
	case Tok_BINARY:
	case Tok_BOOLEAN:
	case Tok_ENUMERATION:
	case Tok_EXTENSIBLE:
	case Tok_INTEGER:
	case Tok_LIST:
	case Tok_LOGICAL:
	case Tok_NUMBER:
	case Tok_REAL:
	case Tok_SELECT:
	case Tok_SET:
	case Tok_STRING:
	case Tok_ident:
		return true;
	default: return false;
	}
}

static inline bool FIRST_concrete_types(int tt) {
	switch(tt){
	case Tok_ARRAY:
	case Tok_BAG:
	case Tok_BINARY:
	case Tok_BOOLEAN:
	case Tok_INTEGER:
	case Tok_LIST:
	case Tok_LOGICAL:
	case Tok_NUMBER:
	case Tok_REAL:
	case Tok_SET:
	case Tok_STRING:
	case Tok_ident:
		return true;
	default: return false;
	}
}

static inline bool FIRST_constructed_types(int tt) {
	return tt == Tok_ENUMERATION || tt == Tok_EXTENSIBLE || tt == Tok_SELECT;
}

static inline bool FIRST_enumeration_items(int tt) {
	return tt == Tok_Lpar;
}

static inline bool FIRST_enumeration_extension(int tt) {
	return tt == Tok_BASED_ON;
}

static inline bool FIRST_select_list(int tt) {
	return tt == Tok_Lpar;
}

static inline bool FIRST_select_extension(int tt) {
	return tt == Tok_BASED_ON;
}

static inline bool FIRST_parameter_type(int tt) {
	switch(tt){
	case Tok_AGGREGATE:
	case Tok_ARRAY:
	case Tok_BAG:
	case Tok_BINARY:
	case Tok_BOOLEAN:
	case Tok_GENERIC:
	case Tok_GENERIC_ENTITY:
	case Tok_INTEGER:
	case Tok_LIST:
	case Tok_LOGICAL:
	case Tok_NUMBER:
	case Tok_REAL:
	case Tok_SET:
	case Tok_STRING:
	case Tok_ident:
		return true;
	default: return false;
	}
}

static inline bool FIRST_generalized_types(int tt) {
	switch(tt){
	case Tok_AGGREGATE:
	case Tok_ARRAY:
	case Tok_BAG:
	case Tok_GENERIC:
	case Tok_GENERIC_ENTITY:
	case Tok_LIST:
	case Tok_SET:
		return true;
	default: return false;
	}
}

static inline bool FIRST_named_types(int tt) {
	return tt == Tok_ident;
}

static inline bool FIRST_simple_types(int tt) {
	switch(tt){
	case Tok_BINARY:
	case Tok_BOOLEAN:
	case Tok_INTEGER:
	case Tok_LOGICAL:
	case Tok_NUMBER:
	case Tok_REAL:
	case Tok_STRING:
		return true;
	default: return false;
	}
}

static inline bool FIRST_binary_type(int tt) {
	return tt == Tok_BINARY;
}

static inline bool FIRST_boolean_type(int tt) {
	return tt == Tok_BOOLEAN;
}

static inline bool FIRST_integer_type(int tt) {
	return tt == Tok_INTEGER;
}

static inline bool FIRST_logical_type(int tt) {
	return tt == Tok_LOGICAL;
}

static inline bool FIRST_number_type(int tt) {
	return tt == Tok_NUMBER;
}

static inline bool FIRST_real_type(int tt) {
	return tt == Tok_REAL;
}

static inline bool FIRST_string_type(int tt) {
	return tt == Tok_STRING;
}

static inline bool FIRST_width_spec(int tt) {
	return tt == Tok_Lpar;
}

static inline bool FIRST_aggregation_types(int tt) {
	return tt == Tok_ARRAY || tt == Tok_BAG || tt == Tok_LIST || tt == Tok_SET;
}

static inline bool FIRST_array_type(int tt) {
	return tt == Tok_ARRAY;
}

static inline bool FIRST_bag_type(int tt) {
	return tt == Tok_BAG;
}

static inline bool FIRST_list_type(int tt) {
	return tt == Tok_LIST;
}

static inline bool FIRST_set_type(int tt) {
	return tt == Tok_SET;
}

static inline bool FIRST_bound_spec(int tt) {
	return tt == Tok_Lbrack;
}

static inline bool FIRST_bound_1(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_bound_2(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_instantiable_type(int tt) {
	switch(tt){
	case Tok_ARRAY:
	case Tok_BAG:
	case Tok_BINARY:
	case Tok_BOOLEAN:
	case Tok_INTEGER:
	case Tok_LIST:
	case Tok_LOGICAL:
	case Tok_NUMBER:
	case Tok_REAL:
	case Tok_SET:
	case Tok_STRING:
	case Tok_ident:
		return true;
	default: return false;
	}
}

static inline bool FIRST_general_aggregation_types(int tt) {
	return tt == Tok_ARRAY || tt == Tok_BAG || tt == Tok_LIST || tt == Tok_SET;
}

static inline bool FIRST_general_array_type(int tt) {
	return tt == Tok_ARRAY;
}

static inline bool FIRST_general_bag_type(int tt) {
	return tt == Tok_BAG;
}

static inline bool FIRST_general_list_type(int tt) {
	return tt == Tok_LIST;
}

static inline bool FIRST_general_set_type(int tt) {
	return tt == Tok_SET;
}

static inline bool FIRST_aggregate_type(int tt) {
	return tt == Tok_AGGREGATE;
}

static inline bool FIRST_type_label(int tt) {
	return tt == Tok_ident;
}

static inline bool FIRST_generic_entity_type(int tt) {
	return tt == Tok_GENERIC_ENTITY;
}

static inline bool FIRST_generic_type(int tt) {
	return tt == Tok_GENERIC;
}

static inline bool FIRST_subtype_constraint_decl(int tt) {
	return tt == Tok_SUBTYPE_CONSTRAINT;
}

static inline bool FIRST_subtype_constraint_head(int tt) {
	return tt == Tok_SUBTYPE_CONSTRAINT;
}

static inline bool FIRST_subtype_constraint_body(int tt) {
	return tt == Tok_ABSTRACT || tt == Tok_Lpar || tt == Tok_ONEOF || tt == Tok_TOTAL_OVER || tt == Tok_ident;
}

static inline bool FIRST_abstract_supertype(int tt) {
	return tt == Tok_ABSTRACT;
}

static inline bool FIRST_total_over(int tt) {
	return tt == Tok_TOTAL_OVER;
}

static inline bool FIRST_function_decl(int tt) {
	return tt == Tok_FUNCTION;
}

static inline bool FIRST_function_head(int tt) {
	return tt == Tok_FUNCTION;
}

static inline bool FIRST_procedure_decl(int tt) {
	return tt == Tok_PROCEDURE;
}

static inline bool FIRST_procedure_head(int tt) {
	return tt == Tok_PROCEDURE;
}

static inline bool FIRST_formal_parameter(int tt) {
	return tt == Tok_ident;
}

static inline bool FIRST_algorithm_head(int tt) {
	switch(tt){
	case Tok_CONSTANT:
	case Tok_ENTITY:
	case Tok_FUNCTION:
	case Tok_LOCAL:
	case Tok_PROCEDURE:
	case Tok_SUBTYPE_CONSTRAINT:
	case Tok_TYPE:
		return true;
	default: return false;
	}
}

static inline bool FIRST_local_decl(int tt) {
	return tt == Tok_LOCAL;
}

static inline bool FIRST_local_variable(int tt) {
	return tt == Tok_ident;
}

static inline bool FIRST_rule_decl(int tt) {
	return tt == Tok_RULE;
}

static inline bool FIRST_rule_head(int tt) {
	return tt == Tok_RULE;
}

static inline bool FIRST_stmt(int tt) {
	switch(tt){
	case Tok_ALIAS:
	case Tok_BEGIN:
	case Tok_CASE:
	case Tok_ESCAPE:
	case Tok_IF:
	case Tok_INSERT:
	case Tok_REMOVE:
	case Tok_REPEAT:
	case Tok_RETURN:
	case Tok_SKIP:
	case Tok_Semi:
	case Tok_ident:
		return true;
	default: return false;
	}
}

static inline bool FIRST_null_stmt(int tt) {
	return tt == Tok_Semi;
}

static inline bool FIRST_assignOrCall_(int tt) {
	return tt == Tok_INSERT || tt == Tok_REMOVE || tt == Tok_ident;
}

static inline bool FIRST_alias_stmt(int tt) {
	return tt == Tok_ALIAS;
}

static inline bool FIRST_case_stmt(int tt) {
	return tt == Tok_CASE;
}

static inline bool FIRST_case_action(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_case_label(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_compound_stmt(int tt) {
	return tt == Tok_BEGIN;
}

static inline bool FIRST_escape_stmt(int tt) {
	return tt == Tok_ESCAPE;
}

static inline bool FIRST_if_stmt(int tt) {
	return tt == Tok_IF;
}

static inline bool FIRST_repeat_stmt(int tt) {
	return tt == Tok_REPEAT;
}

static inline bool FIRST_repeat_control(int tt) {
	return tt == Tok_UNTIL || tt == Tok_WHILE || tt == Tok_ident;
}

static inline bool FIRST_increment_control(int tt) {
	return tt == Tok_ident;
}

static inline bool FIRST_while_control(int tt) {
	return tt == Tok_WHILE;
}

static inline bool FIRST_until_control(int tt) {
	return tt == Tok_UNTIL;
}

static inline bool FIRST_return_stmt(int tt) {
	return tt == Tok_RETURN;
}

static inline bool FIRST_skip_stmt(int tt) {
	return tt == Tok_SKIP;
}

static inline bool FIRST_expression(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_and_expression(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_rel_expression(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_simple_expression(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_term(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_factor(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_simple_factor(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_primary(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_actual_parameter_list(int tt) {
	return tt == Tok_Lpar;
}

static inline bool FIRST_qualifier(int tt) {
	return tt == Tok_Bslash || tt == Tok_Dot || tt == Tok_Lbrack || tt == Tok_Lpar;
}

static inline bool FIRST_attribute_qualifier(int tt) {
	return tt == Tok_Dot;
}

static inline bool FIRST_group_qualifier(int tt) {
	return tt == Tok_Bslash;
}

static inline bool FIRST_index_qualifier(int tt) {
	return tt == Tok_Lbrack;
}

static inline bool FIRST_index_1(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_index_2(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_numeric_expression(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_aggregate_initializer(int tt) {
	return tt == Tok_Lbrack;
}

static inline bool FIRST_element(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_repetition(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_interval(int tt) {
	return tt == Tok_Lbrace;
}

static inline bool FIRST_interval_op(int tt) {
	return tt == Tok_Leq || tt == Tok_Lt;
}

static inline bool FIRST_query_expression(int tt) {
	return tt == Tok_QUERY;
}

static inline bool FIRST_rel_op_extended(int tt) {
	switch(tt){
	case Tok_ColonEqColon:
	case Tok_ColonLtGtColon:
	case Tok_Eq:
	case Tok_Geq:
	case Tok_Gt:
	case Tok_IN:
	case Tok_LIKE:
	case Tok_Leq:
	case Tok_Lt:
	case Tok_LtGt:
		return true;
	default: return false;
	}
}

static inline bool FIRST_rel_op(int tt) {
	switch(tt){
	case Tok_ColonEqColon:
	case Tok_ColonLtGtColon:
	case Tok_Eq:
	case Tok_Geq:
	case Tok_Gt:
	case Tok_Leq:
	case Tok_Lt:
	case Tok_LtGt:
		return true;
	default: return false;
	}
}

static inline bool FIRST_add_like_op(int tt) {
	return tt == Tok_Minus || tt == Tok_Plus || tt == Tok_XOR;
}

static inline bool FIRST_multiplication_like_op(int tt) {
	return tt == Tok_2Bar || tt == Tok_DIV || tt == Tok_MOD || tt == Tok_Slash || tt == Tok_Star;
}

static inline bool FIRST_unary_op(int tt) {
	return tt == Tok_Minus || tt == Tok_NOT || tt == Tok_Plus;
}

static inline bool FIRST_built_in_constant(int tt) {
	return tt == Tok_CONST_E || tt == Tok_PI || tt == Tok_Qmark || tt == Tok_SELF;
}

static inline bool FIRST_built_in_function(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_ROLESOF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TYPEOF:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
		return true;
	default: return false;
	}
}

static inline bool FIRST_built_in_procedure(int tt) {
	return tt == Tok_INSERT || tt == Tok_REMOVE;
}

static inline bool FIRST_where_clause(int tt) {
	return tt == Tok_WHERE;
}

static inline bool FIRST_domain_rule(int tt) {
	switch(tt){
	case Tok_ABS:
	case Tok_ACOS:
	case Tok_ASIN:
	case Tok_ATAN:
	case Tok_BLENGTH:
	case Tok_CONST_E:
	case Tok_COS:
	case Tok_EXISTS:
	case Tok_EXP:
	case Tok_FALSE:
	case Tok_FORMAT:
	case Tok_HIBOUND:
	case Tok_HIINDEX:
	case Tok_LENGTH:
	case Tok_LOBOUND:
	case Tok_LOG:
	case Tok_LOG10:
	case Tok_LOG2:
	case Tok_LOINDEX:
	case Tok_Lbrace:
	case Tok_Lbrack:
	case Tok_Lpar:
	case Tok_Minus:
	case Tok_NOT:
	case Tok_NVL:
	case Tok_ODD:
	case Tok_PI:
	case Tok_Plus:
	case Tok_QUERY:
	case Tok_Qmark:
	case Tok_ROLESOF:
	case Tok_SELF:
	case Tok_SIN:
	case Tok_SIZEOF:
	case Tok_SQRT:
	case Tok_TAN:
	case Tok_TRUE:
	case Tok_TYPEOF:
	case Tok_UNKNOWN:
	case Tok_USEDIN:
	case Tok_VALUE:
	case Tok_VALUE_IN:
	case Tok_VALUE_UNIQUE:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_ident:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_string_literal(int tt) {
	return tt == Tok_encoded_string_literal || tt == Tok_simple_string_literal;
}

static inline bool FIRST_literal(int tt) {
	switch(tt){
	case Tok_FALSE:
	case Tok_TRUE:
	case Tok_UNKNOWN:
	case Tok_binary_literal:
	case Tok_encoded_string_literal:
	case Tok_integer_literal:
	case Tok_real_literal:
	case Tok_simple_string_literal:
		return true;
	default: return false;
	}
}

static inline bool FIRST_logical_literal(int tt) {
	return tt == Tok_FALSE || tt == Tok_TRUE || tt == Tok_UNKNOWN;
}

void Parser::RunParser() {
	errors.clear();
	next();
	syntax();
}

void Parser::next() {
	cur = la;
	la = scanner->next();
	while( la.d_type == Tok_Invalid ) {
		errors << Error(la.d_val, la.d_lineNr, la.d_colNr, la.d_sourcePath);
		la = scanner->next();
	}
}

Token Parser::peek(int off) {
	if( off == 1 )
		return la;
	else if( off == 0 )
		return cur;
	else
		return scanner->peek(off-1);
}

void Parser::invalid(const char* what) {
	errors << Error(QString("invalid %1").arg(what),la.d_lineNr, la.d_colNr, la.d_sourcePath);
}

bool Parser::expect(int tt, bool pkw, const char* where) {
	if( la.d_type == tt) { next(); return true; }
	else { errors << Error(QString("'%1' expected in %2").arg(tokenTypeString(tt)).arg(where),la.d_lineNr, la.d_colNr, la.d_sourcePath); return false; }
}

static inline void dummy() {}

void Parser::syntax() {
	schema_decl();
	while( FIRST_schema_decl(la.d_type) ) {
		schema_decl();
	}
}

void Parser::schema_decl() {
	expect(Tok_SCHEMA, false, "schema_decl");
	expect(Tok_ident, false, "schema_decl");
	if( FIRST_string_literal(la.d_type) ) {
		string_literal();
	}
	expect(Tok_Semi, false, "schema_decl");
	schema_body();
	expect(Tok_END_SCHEMA, false, "schema_decl");
	expect(Tok_Semi, false, "schema_decl");
}

void Parser::schema_body() {
	while( FIRST_interface_specification(la.d_type) ) {
		interface_specification();
	}
	if( FIRST_constant_decl(la.d_type) ) {
		constant_decl();
	}
	while( FIRST_declaration(la.d_type) || FIRST_rule_decl(la.d_type) ) {
		if( FIRST_declaration(la.d_type) ) {
			declaration();
		} else if( FIRST_rule_decl(la.d_type) ) {
			rule_decl();
		} else
			invalid("schema_body");
	}
}

void Parser::interface_specification() {
	if( FIRST_reference_clause(la.d_type) ) {
		reference_clause();
	} else if( FIRST_use_clause(la.d_type) ) {
		use_clause();
	} else
		invalid("interface_specification");
}

void Parser::reference_clause() {
	expect(Tok_REFERENCE, false, "reference_clause");
	expect(Tok_FROM, false, "reference_clause");
	expect(Tok_ident, false, "reference_clause");
	if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "reference_clause");
		resource_or_rename();
		while( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "reference_clause");
			resource_or_rename();
		}
		expect(Tok_Rpar, false, "reference_clause");
	}
	expect(Tok_Semi, false, "reference_clause");
}

void Parser::use_clause() {
	expect(Tok_USE, false, "use_clause");
	expect(Tok_FROM, false, "use_clause");
	expect(Tok_ident, false, "use_clause");
	if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "use_clause");
		named_type_or_rename();
		while( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "use_clause");
			named_type_or_rename();
		}
		expect(Tok_Rpar, false, "use_clause");
	}
	expect(Tok_Semi, false, "use_clause");
}

void Parser::resource_or_rename() {
	expect(Tok_ident, false, "resource_or_rename");
	if( la.d_type == Tok_AS ) {
		expect(Tok_AS, false, "resource_or_rename");
		expect(Tok_ident, false, "resource_or_rename");
	}
}

void Parser::named_type_or_rename() {
	expect(Tok_ident, false, "named_type_or_rename");
	if( la.d_type == Tok_AS ) {
		expect(Tok_AS, false, "named_type_or_rename");
		expect(Tok_ident, false, "named_type_or_rename");
	}
}

void Parser::declaration() {
	if( FIRST_entity_decl(la.d_type) ) {
		entity_decl();
	} else if( FIRST_function_decl(la.d_type) ) {
		function_decl();
	} else if( FIRST_procedure_decl(la.d_type) ) {
		procedure_decl();
	} else if( FIRST_subtype_constraint_decl(la.d_type) ) {
		subtype_constraint_decl();
	} else if( FIRST_type_decl(la.d_type) ) {
		type_decl();
	} else
		invalid("declaration");
}

void Parser::constant_decl() {
	expect(Tok_CONSTANT, false, "constant_decl");
	constant_body();
	while( FIRST_constant_body(la.d_type) ) {
		constant_body();
	}
	expect(Tok_END_CONSTANT, false, "constant_decl");
	expect(Tok_Semi, false, "constant_decl");
}

void Parser::constant_body() {
	expect(Tok_ident, false, "constant_body");
	expect(Tok_Colon, false, "constant_body");
	instantiable_type();
	expect(Tok_ColonEq, false, "constant_body");
	expression();
	expect(Tok_Semi, false, "constant_body");
}

void Parser::entity_decl() {
	entity_head();
	entity_body();
	expect(Tok_END_ENTITY, false, "entity_decl");
	expect(Tok_Semi, false, "entity_decl");
}

void Parser::entity_head() {
	expect(Tok_ENTITY, false, "entity_head");
	expect(Tok_ident, false, "entity_head");
	subsuper();
	expect(Tok_Semi, false, "entity_head");
}

void Parser::subsuper() {
	if( FIRST_supertype_constraint(la.d_type) ) {
		supertype_constraint();
	}
	if( FIRST_subtype_declaration(la.d_type) ) {
		subtype_declaration();
	}
}

void Parser::supertype_constraint() {
	if( la.d_type == Tok_ABSTRACT ) {
		expect(Tok_ABSTRACT, false, "supertype_constraint");
		if( la.d_type == Tok_SUPERTYPE ) {
			expect(Tok_SUPERTYPE, false, "supertype_constraint");
			if( FIRST_subtype_constraint(la.d_type) ) {
				subtype_constraint();
			}
		}
	} else if( la.d_type == Tok_SUPERTYPE ) {
		expect(Tok_SUPERTYPE, false, "supertype_constraint");
		subtype_constraint();
	} else
		invalid("supertype_constraint");
}

void Parser::subtype_constraint() {
	expect(Tok_OF, false, "subtype_constraint");
	expect(Tok_Lpar, false, "subtype_constraint");
	supertype_expression();
	expect(Tok_Rpar, false, "subtype_constraint");
}

void Parser::subtype_declaration() {
	expect(Tok_SUBTYPE, false, "subtype_declaration");
	expect(Tok_OF, false, "subtype_declaration");
	expect(Tok_Lpar, false, "subtype_declaration");
	expect(Tok_ident, false, "subtype_declaration");
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "subtype_declaration");
		expect(Tok_ident, false, "subtype_declaration");
	}
	expect(Tok_Rpar, false, "subtype_declaration");
}

void Parser::supertype_expression() {
	supertype_factor();
	while( la.d_type == Tok_ANDOR ) {
		expect(Tok_ANDOR, false, "supertype_expression");
		supertype_factor();
	}
}

void Parser::supertype_factor() {
	supertype_term();
	while( la.d_type == Tok_AND ) {
		expect(Tok_AND, false, "supertype_factor");
		supertype_term();
	}
}

void Parser::supertype_term() {
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "supertype_term");
	} else if( FIRST_one_of(la.d_type) ) {
		one_of();
	} else if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "supertype_term");
		supertype_expression();
		expect(Tok_Rpar, false, "supertype_term");
	} else
		invalid("supertype_term");
}

void Parser::one_of() {
	expect(Tok_ONEOF, false, "one_of");
	expect(Tok_Lpar, false, "one_of");
	supertype_expression();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "one_of");
		supertype_expression();
	}
	expect(Tok_Rpar, false, "one_of");
}

void Parser::entity_body() {
	while( FIRST_explicit_attr(la.d_type) ) {
		explicit_attr();
	}
	if( FIRST_derive_clause(la.d_type) ) {
		derive_clause();
	}
	if( FIRST_inverse_clause(la.d_type) ) {
		inverse_clause();
	}
	if( FIRST_unique_clause(la.d_type) ) {
		unique_clause();
	}
	if( FIRST_where_clause(la.d_type) ) {
		where_clause();
	}
}

void Parser::explicit_attr() {
	attribute_decl();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "explicit_attr");
		attribute_decl();
	}
	expect(Tok_Colon, false, "explicit_attr");
	if( la.d_type == Tok_OPTIONAL ) {
		expect(Tok_OPTIONAL, false, "explicit_attr");
	}
	parameter_type();
	expect(Tok_Semi, false, "explicit_attr");
}

void Parser::attribute_decl() {
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "attribute_decl");
	} else if( FIRST_redeclared_attribute(la.d_type) ) {
		redeclared_attribute();
	} else
		invalid("attribute_decl");
}

void Parser::redeclared_attribute() {
	qualified_attribute();
	if( la.d_type == Tok_RENAMED ) {
		expect(Tok_RENAMED, false, "redeclared_attribute");
		expect(Tok_ident, false, "redeclared_attribute");
	}
}

void Parser::qualified_attribute() {
	expect(Tok_SELF, false, "qualified_attribute");
	group_qualifier();
	attribute_qualifier();
}

void Parser::derive_clause() {
	expect(Tok_DERIVE, false, "derive_clause");
	derived_attr();
	while( FIRST_derived_attr(la.d_type) ) {
		derived_attr();
	}
}

void Parser::derived_attr() {
	attribute_decl();
	expect(Tok_Colon, false, "derived_attr");
	parameter_type();
	expect(Tok_ColonEq, false, "derived_attr");
	expression();
	expect(Tok_Semi, false, "derived_attr");
}

void Parser::inverse_clause() {
	expect(Tok_INVERSE, false, "inverse_clause");
	inverse_attr();
	while( FIRST_inverse_attr(la.d_type) ) {
		inverse_attr();
	}
}

void Parser::inverse_attr() {
	attribute_decl();
	expect(Tok_Colon, false, "inverse_attr");
	if( la.d_type == Tok_SET || la.d_type == Tok_BAG ) {
		if( la.d_type == Tok_SET ) {
			expect(Tok_SET, false, "inverse_attr");
		} else if( la.d_type == Tok_BAG ) {
			expect(Tok_BAG, false, "inverse_attr");
		} else
			invalid("inverse_attr");
		if( FIRST_bound_spec(la.d_type) ) {
			bound_spec();
		}
		expect(Tok_OF, false, "inverse_attr");
	}
	expect(Tok_ident, false, "inverse_attr");
	expect(Tok_FOR, false, "inverse_attr");
	if( la.d_type == Tok_SELF ) {
		expect(Tok_SELF, false, "inverse_attr");
		while( FIRST_qualifier(la.d_type) ) {
			qualifier();
		}
	} else if( ( peek(1).d_type == Tok_ident && peek(2).d_type == Tok_Dot )  || la.d_type == Tok_ident ) {
		if( ( peek(1).d_type == Tok_ident && peek(2).d_type == Tok_Dot )  ) {
			expect(Tok_ident, false, "inverse_attr");
			expect(Tok_Dot, false, "inverse_attr");
		}
		expect(Tok_ident, false, "inverse_attr");
	} else
		invalid("inverse_attr");
	expect(Tok_Semi, false, "inverse_attr");
}

void Parser::unique_clause() {
	expect(Tok_UNIQUE, false, "unique_clause");
	unique_rule();
	expect(Tok_Semi, false, "unique_clause");
	while( FIRST_unique_rule(la.d_type) ) {
		unique_rule();
		expect(Tok_Semi, false, "unique_clause");
	}
}

void Parser::unique_rule() {
	if( ( peek(1).d_type == Tok_ident && peek(2).d_type == Tok_Colon )  ) {
		expect(Tok_ident, false, "unique_rule");
		expect(Tok_Colon, false, "unique_rule");
	}
	referenced_attribute();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "unique_rule");
		referenced_attribute();
	}
}

void Parser::referenced_attribute() {
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "referenced_attribute");
	} else if( FIRST_qualified_attribute(la.d_type) ) {
		qualified_attribute();
	} else
		invalid("referenced_attribute");
}

void Parser::type_decl() {
	expect(Tok_TYPE, false, "type_decl");
	expect(Tok_ident, false, "type_decl");
	expect(Tok_Eq, false, "type_decl");
	underlying_type();
	expect(Tok_Semi, false, "type_decl");
	if( FIRST_where_clause(la.d_type) ) {
		where_clause();
	}
	expect(Tok_END_TYPE, false, "type_decl");
	expect(Tok_Semi, false, "type_decl");
}

void Parser::underlying_type() {
	if( FIRST_concrete_types(la.d_type) ) {
		concrete_types();
	} else if( FIRST_constructed_types(la.d_type) ) {
		constructed_types();
	} else
		invalid("underlying_type");
}

void Parser::concrete_types() {
	if( FIRST_aggregation_types(la.d_type) ) {
		aggregation_types();
	} else if( FIRST_simple_types(la.d_type) ) {
		simple_types();
	} else if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "concrete_types");
	} else
		invalid("concrete_types");
}

void Parser::constructed_types() {
	if( la.d_type == Tok_EXTENSIBLE ) {
		expect(Tok_EXTENSIBLE, false, "constructed_types");
		if( la.d_type == Tok_ENUMERATION ) {
			expect(Tok_ENUMERATION, false, "constructed_types");
			if( la.d_type == Tok_OF || FIRST_enumeration_extension(la.d_type) ) {
				if( la.d_type == Tok_OF ) {
					expect(Tok_OF, false, "constructed_types");
					enumeration_items();
				} else if( FIRST_enumeration_extension(la.d_type) ) {
					enumeration_extension();
				} else
					invalid("constructed_types");
			}
		} else if( la.d_type == Tok_GENERIC_ENTITY || la.d_type == Tok_SELECT ) {
			if( la.d_type == Tok_GENERIC_ENTITY ) {
				expect(Tok_GENERIC_ENTITY, false, "constructed_types");
			}
			expect(Tok_SELECT, false, "constructed_types");
			if( FIRST_select_list(la.d_type) || FIRST_select_extension(la.d_type) ) {
				if( FIRST_select_list(la.d_type) ) {
					select_list();
				} else if( FIRST_select_extension(la.d_type) ) {
					select_extension();
				} else
					invalid("constructed_types");
			}
		} else
			invalid("constructed_types");
	} else if( la.d_type == Tok_ENUMERATION ) {
		expect(Tok_ENUMERATION, false, "constructed_types");
		if( la.d_type == Tok_OF || FIRST_enumeration_extension(la.d_type) ) {
			if( la.d_type == Tok_OF ) {
				expect(Tok_OF, false, "constructed_types");
				enumeration_items();
			} else if( FIRST_enumeration_extension(la.d_type) ) {
				enumeration_extension();
			} else
				invalid("constructed_types");
		}
	} else if( la.d_type == Tok_SELECT ) {
		expect(Tok_SELECT, false, "constructed_types");
		if( FIRST_select_list(la.d_type) || FIRST_select_extension(la.d_type) ) {
			if( FIRST_select_list(la.d_type) ) {
				select_list();
			} else if( FIRST_select_extension(la.d_type) ) {
				select_extension();
			} else
				invalid("constructed_types");
		}
	} else
		invalid("constructed_types");
}

void Parser::enumeration_items() {
	expect(Tok_Lpar, false, "enumeration_items");
	expect(Tok_ident, false, "enumeration_items");
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "enumeration_items");
		expect(Tok_ident, false, "enumeration_items");
	}
	expect(Tok_Rpar, false, "enumeration_items");
}

void Parser::enumeration_extension() {
	expect(Tok_BASED_ON, false, "enumeration_extension");
	expect(Tok_ident, false, "enumeration_extension");
	if( la.d_type == Tok_WITH ) {
		expect(Tok_WITH, false, "enumeration_extension");
		enumeration_items();
	}
}

void Parser::select_list() {
	expect(Tok_Lpar, false, "select_list");
	expect(Tok_ident, false, "select_list");
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "select_list");
		expect(Tok_ident, false, "select_list");
	}
	expect(Tok_Rpar, false, "select_list");
}

void Parser::select_extension() {
	expect(Tok_BASED_ON, false, "select_extension");
	expect(Tok_ident, false, "select_extension");
	if( la.d_type == Tok_WITH ) {
		expect(Tok_WITH, false, "select_extension");
		select_list();
	}
}

void Parser::parameter_type() {
	if( FIRST_generalized_types(la.d_type) ) {
		generalized_types();
	} else if( FIRST_named_types(la.d_type) ) {
		named_types();
	} else if( FIRST_simple_types(la.d_type) ) {
		simple_types();
	} else
		invalid("parameter_type");
}

void Parser::generalized_types() {
	if( FIRST_aggregate_type(la.d_type) ) {
		aggregate_type();
	} else if( FIRST_general_aggregation_types(la.d_type) ) {
		general_aggregation_types();
	} else if( FIRST_generic_entity_type(la.d_type) ) {
		generic_entity_type();
	} else if( FIRST_generic_type(la.d_type) ) {
		generic_type();
	} else
		invalid("generalized_types");
}

void Parser::named_types() {
	expect(Tok_ident, false, "named_types");
}

void Parser::simple_types() {
	if( FIRST_binary_type(la.d_type) ) {
		binary_type();
	} else if( FIRST_boolean_type(la.d_type) ) {
		boolean_type();
	} else if( FIRST_integer_type(la.d_type) ) {
		integer_type();
	} else if( FIRST_logical_type(la.d_type) ) {
		logical_type();
	} else if( FIRST_number_type(la.d_type) ) {
		number_type();
	} else if( FIRST_real_type(la.d_type) ) {
		real_type();
	} else if( FIRST_string_type(la.d_type) ) {
		string_type();
	} else
		invalid("simple_types");
}

void Parser::binary_type() {
	expect(Tok_BINARY, false, "binary_type");
	if( FIRST_width_spec(la.d_type) ) {
		width_spec();
	}
}

void Parser::boolean_type() {
	expect(Tok_BOOLEAN, false, "boolean_type");
}

void Parser::integer_type() {
	expect(Tok_INTEGER, false, "integer_type");
}

void Parser::logical_type() {
	expect(Tok_LOGICAL, false, "logical_type");
}

void Parser::number_type() {
	expect(Tok_NUMBER, false, "number_type");
}

void Parser::real_type() {
	expect(Tok_REAL, false, "real_type");
	if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "real_type");
		numeric_expression();
		expect(Tok_Rpar, false, "real_type");
	}
}

void Parser::string_type() {
	expect(Tok_STRING, false, "string_type");
	if( FIRST_width_spec(la.d_type) ) {
		width_spec();
	}
}

void Parser::width_spec() {
	expect(Tok_Lpar, false, "width_spec");
	numeric_expression();
	expect(Tok_Rpar, false, "width_spec");
	if( la.d_type == Tok_FIXED ) {
		expect(Tok_FIXED, false, "width_spec");
	}
}

void Parser::aggregation_types() {
	if( FIRST_array_type(la.d_type) ) {
		array_type();
	} else if( FIRST_bag_type(la.d_type) ) {
		bag_type();
	} else if( FIRST_list_type(la.d_type) ) {
		list_type();
	} else if( FIRST_set_type(la.d_type) ) {
		set_type();
	} else
		invalid("aggregation_types");
}

void Parser::array_type() {
	expect(Tok_ARRAY, false, "array_type");
	bound_spec();
	expect(Tok_OF, false, "array_type");
	if( la.d_type == Tok_OPTIONAL ) {
		expect(Tok_OPTIONAL, false, "array_type");
	}
	if( la.d_type == Tok_UNIQUE ) {
		expect(Tok_UNIQUE, false, "array_type");
	}
	instantiable_type();
}

void Parser::bag_type() {
	expect(Tok_BAG, false, "bag_type");
	if( FIRST_bound_spec(la.d_type) ) {
		bound_spec();
	}
	expect(Tok_OF, false, "bag_type");
	instantiable_type();
}

void Parser::list_type() {
	expect(Tok_LIST, false, "list_type");
	if( FIRST_bound_spec(la.d_type) ) {
		bound_spec();
	}
	expect(Tok_OF, false, "list_type");
	if( la.d_type == Tok_UNIQUE ) {
		expect(Tok_UNIQUE, false, "list_type");
	}
	instantiable_type();
}

void Parser::set_type() {
	expect(Tok_SET, false, "set_type");
	if( FIRST_bound_spec(la.d_type) ) {
		bound_spec();
	}
	expect(Tok_OF, false, "set_type");
	instantiable_type();
}

void Parser::bound_spec() {
	expect(Tok_Lbrack, false, "bound_spec");
	bound_1();
	expect(Tok_Colon, false, "bound_spec");
	bound_2();
	expect(Tok_Rbrack, false, "bound_spec");
}

void Parser::bound_1() {
	numeric_expression();
}

void Parser::bound_2() {
	numeric_expression();
}

void Parser::instantiable_type() {
	concrete_types();
}

void Parser::general_aggregation_types() {
	if( FIRST_general_array_type(la.d_type) ) {
		general_array_type();
	} else if( FIRST_general_bag_type(la.d_type) ) {
		general_bag_type();
	} else if( FIRST_general_list_type(la.d_type) ) {
		general_list_type();
	} else if( FIRST_general_set_type(la.d_type) ) {
		general_set_type();
	} else
		invalid("general_aggregation_types");
}

void Parser::general_array_type() {
	expect(Tok_ARRAY, false, "general_array_type");
	if( FIRST_bound_spec(la.d_type) ) {
		bound_spec();
	}
	expect(Tok_OF, false, "general_array_type");
	if( la.d_type == Tok_OPTIONAL ) {
		expect(Tok_OPTIONAL, false, "general_array_type");
	}
	if( la.d_type == Tok_UNIQUE ) {
		expect(Tok_UNIQUE, false, "general_array_type");
	}
	parameter_type();
}

void Parser::general_bag_type() {
	expect(Tok_BAG, false, "general_bag_type");
	if( FIRST_bound_spec(la.d_type) ) {
		bound_spec();
	}
	expect(Tok_OF, false, "general_bag_type");
	parameter_type();
}

void Parser::general_list_type() {
	expect(Tok_LIST, false, "general_list_type");
	if( FIRST_bound_spec(la.d_type) ) {
		bound_spec();
	}
	expect(Tok_OF, false, "general_list_type");
	if( la.d_type == Tok_UNIQUE ) {
		expect(Tok_UNIQUE, false, "general_list_type");
	}
	parameter_type();
}

void Parser::general_set_type() {
	expect(Tok_SET, false, "general_set_type");
	if( FIRST_bound_spec(la.d_type) ) {
		bound_spec();
	}
	expect(Tok_OF, false, "general_set_type");
	parameter_type();
}

void Parser::aggregate_type() {
	expect(Tok_AGGREGATE, false, "aggregate_type");
	if( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "aggregate_type");
		type_label();
	}
	expect(Tok_OF, false, "aggregate_type");
	parameter_type();
}

void Parser::type_label() {
	expect(Tok_ident, false, "type_label");
}

void Parser::generic_entity_type() {
	expect(Tok_GENERIC_ENTITY, false, "generic_entity_type");
	if( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "generic_entity_type");
		type_label();
	}
}

void Parser::generic_type() {
	expect(Tok_GENERIC, false, "generic_type");
	if( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "generic_type");
		type_label();
	}
}

void Parser::subtype_constraint_decl() {
	subtype_constraint_head();
	subtype_constraint_body();
	expect(Tok_END_SUBTYPE_CONSTRAINT, false, "subtype_constraint_decl");
	expect(Tok_Semi, false, "subtype_constraint_decl");
}

void Parser::subtype_constraint_head() {
	expect(Tok_SUBTYPE_CONSTRAINT, false, "subtype_constraint_head");
	expect(Tok_ident, false, "subtype_constraint_head");
	expect(Tok_FOR, false, "subtype_constraint_head");
	expect(Tok_ident, false, "subtype_constraint_head");
	expect(Tok_Semi, false, "subtype_constraint_head");
}

void Parser::subtype_constraint_body() {
	if( FIRST_abstract_supertype(la.d_type) ) {
		abstract_supertype();
	}
	if( FIRST_total_over(la.d_type) ) {
		total_over();
	}
	if( FIRST_supertype_expression(la.d_type) ) {
		supertype_expression();
		expect(Tok_Semi, false, "subtype_constraint_body");
	}
}

void Parser::abstract_supertype() {
	expect(Tok_ABSTRACT, false, "abstract_supertype");
	expect(Tok_SUPERTYPE, false, "abstract_supertype");
	expect(Tok_Semi, false, "abstract_supertype");
}

void Parser::total_over() {
	expect(Tok_TOTAL_OVER, false, "total_over");
	expect(Tok_Lpar, false, "total_over");
	expect(Tok_ident, false, "total_over");
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "total_over");
		expect(Tok_ident, false, "total_over");
	}
	expect(Tok_Rpar, false, "total_over");
	expect(Tok_Semi, false, "total_over");
}

void Parser::function_decl() {
	function_head();
	algorithm_head();
	stmt();
	while( FIRST_stmt(la.d_type) ) {
		stmt();
	}
	expect(Tok_END_FUNCTION, false, "function_decl");
	expect(Tok_Semi, false, "function_decl");
}

void Parser::function_head() {
	expect(Tok_FUNCTION, false, "function_head");
	expect(Tok_ident, false, "function_head");
	if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "function_head");
		formal_parameter();
		while( la.d_type == Tok_Semi ) {
			expect(Tok_Semi, false, "function_head");
			formal_parameter();
		}
		expect(Tok_Rpar, false, "function_head");
	}
	expect(Tok_Colon, false, "function_head");
	parameter_type();
	expect(Tok_Semi, false, "function_head");
}

void Parser::procedure_decl() {
	procedure_head();
	algorithm_head();
	while( FIRST_stmt(la.d_type) ) {
		stmt();
	}
	expect(Tok_END_PROCEDURE, false, "procedure_decl");
	expect(Tok_Semi, false, "procedure_decl");
}

void Parser::procedure_head() {
	expect(Tok_PROCEDURE, false, "procedure_head");
	expect(Tok_ident, false, "procedure_head");
	if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "procedure_head");
		if( la.d_type == Tok_VAR ) {
			expect(Tok_VAR, false, "procedure_head");
		}
		formal_parameter();
		while( la.d_type == Tok_Semi ) {
			expect(Tok_Semi, false, "procedure_head");
			if( la.d_type == Tok_VAR ) {
				expect(Tok_VAR, false, "procedure_head");
			}
			formal_parameter();
		}
		expect(Tok_Rpar, false, "procedure_head");
	}
	expect(Tok_Semi, false, "procedure_head");
}

void Parser::formal_parameter() {
	expect(Tok_ident, false, "formal_parameter");
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "formal_parameter");
		expect(Tok_ident, false, "formal_parameter");
	}
	expect(Tok_Colon, false, "formal_parameter");
	parameter_type();
}

void Parser::algorithm_head() {
	while( FIRST_declaration(la.d_type) ) {
		declaration();
	}
	if( FIRST_constant_decl(la.d_type) ) {
		constant_decl();
	}
	if( FIRST_local_decl(la.d_type) ) {
		local_decl();
	}
}

void Parser::local_decl() {
	expect(Tok_LOCAL, false, "local_decl");
	local_variable();
	while( FIRST_local_variable(la.d_type) ) {
		local_variable();
	}
	expect(Tok_END_LOCAL, false, "local_decl");
	expect(Tok_Semi, false, "local_decl");
}

void Parser::local_variable() {
	expect(Tok_ident, false, "local_variable");
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "local_variable");
		expect(Tok_ident, false, "local_variable");
	}
	expect(Tok_Colon, false, "local_variable");
	parameter_type();
	if( la.d_type == Tok_ColonEq ) {
		expect(Tok_ColonEq, false, "local_variable");
		expression();
	}
	expect(Tok_Semi, false, "local_variable");
}

void Parser::rule_decl() {
	rule_head();
	algorithm_head();
	while( FIRST_stmt(la.d_type) ) {
		stmt();
	}
	where_clause();
	expect(Tok_END_RULE, false, "rule_decl");
	expect(Tok_Semi, false, "rule_decl");
}

void Parser::rule_head() {
	expect(Tok_RULE, false, "rule_head");
	expect(Tok_ident, false, "rule_head");
	expect(Tok_FOR, false, "rule_head");
	expect(Tok_Lpar, false, "rule_head");
	expect(Tok_ident, false, "rule_head");
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "rule_head");
		expect(Tok_ident, false, "rule_head");
	}
	expect(Tok_Rpar, false, "rule_head");
	expect(Tok_Semi, false, "rule_head");
}

void Parser::stmt() {
	if( FIRST_alias_stmt(la.d_type) ) {
		alias_stmt();
	} else if( FIRST_assignOrCall_(la.d_type) ) {
		assignOrCall_();
		expect(Tok_Semi, false, "stmt");
	} else if( FIRST_case_stmt(la.d_type) ) {
		case_stmt();
	} else if( FIRST_compound_stmt(la.d_type) ) {
		compound_stmt();
	} else if( FIRST_escape_stmt(la.d_type) ) {
		escape_stmt();
	} else if( FIRST_if_stmt(la.d_type) ) {
		if_stmt();
	} else if( FIRST_null_stmt(la.d_type) ) {
		null_stmt();
	} else if( FIRST_repeat_stmt(la.d_type) ) {
		repeat_stmt();
	} else if( FIRST_return_stmt(la.d_type) ) {
		return_stmt();
	} else if( FIRST_skip_stmt(la.d_type) ) {
		skip_stmt();
	} else
		invalid("stmt");
}

void Parser::null_stmt() {
	expect(Tok_Semi, false, "null_stmt");
}

void Parser::assignOrCall_() {
	if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "assignOrCall_");
		while( FIRST_qualifier(la.d_type) ) {
			qualifier();
		}
		if( la.d_type == Tok_ColonEq ) {
			expect(Tok_ColonEq, false, "assignOrCall_");
			expression();
		}
	} else if( FIRST_built_in_procedure(la.d_type) ) {
		built_in_procedure();
		if( FIRST_actual_parameter_list(la.d_type) ) {
			actual_parameter_list();
		}
	} else
		invalid("assignOrCall_");
}

void Parser::alias_stmt() {
	expect(Tok_ALIAS, false, "alias_stmt");
	expect(Tok_ident, false, "alias_stmt");
	expect(Tok_FOR, false, "alias_stmt");
	expect(Tok_ident, false, "alias_stmt");
	while( FIRST_qualifier(la.d_type) ) {
		qualifier();
	}
	expect(Tok_Semi, false, "alias_stmt");
	stmt();
	while( FIRST_stmt(la.d_type) ) {
		stmt();
	}
	expect(Tok_END_ALIAS, false, "alias_stmt");
	expect(Tok_Semi, false, "alias_stmt");
}

void Parser::case_stmt() {
	expect(Tok_CASE, false, "case_stmt");
	expression();
	expect(Tok_OF, false, "case_stmt");
	while( FIRST_case_action(la.d_type) ) {
		case_action();
	}
	if( la.d_type == Tok_OTHERWISE ) {
		expect(Tok_OTHERWISE, false, "case_stmt");
		expect(Tok_Colon, false, "case_stmt");
		stmt();
	}
	expect(Tok_END_CASE, false, "case_stmt");
	expect(Tok_Semi, false, "case_stmt");
}

void Parser::case_action() {
	case_label();
	while( la.d_type == Tok_Comma ) {
		expect(Tok_Comma, false, "case_action");
		case_label();
	}
	expect(Tok_Colon, false, "case_action");
	stmt();
}

void Parser::case_label() {
	expression();
}

void Parser::compound_stmt() {
	expect(Tok_BEGIN, false, "compound_stmt");
	stmt();
	while( FIRST_stmt(la.d_type) ) {
		stmt();
	}
	expect(Tok_END, false, "compound_stmt");
	expect(Tok_Semi, false, "compound_stmt");
}

void Parser::escape_stmt() {
	expect(Tok_ESCAPE, false, "escape_stmt");
	expect(Tok_Semi, false, "escape_stmt");
}

void Parser::if_stmt() {
	expect(Tok_IF, false, "if_stmt");
	expression();
	expect(Tok_THEN, false, "if_stmt");
	stmt();
	while( FIRST_stmt(la.d_type) ) {
		stmt();
	}
	if( la.d_type == Tok_ELSE ) {
		expect(Tok_ELSE, false, "if_stmt");
		stmt();
		while( FIRST_stmt(la.d_type) ) {
			stmt();
		}
	}
	expect(Tok_END_IF, false, "if_stmt");
	expect(Tok_Semi, false, "if_stmt");
}

void Parser::repeat_stmt() {
	expect(Tok_REPEAT, false, "repeat_stmt");
	repeat_control();
	expect(Tok_Semi, false, "repeat_stmt");
	stmt();
	while( FIRST_stmt(la.d_type) ) {
		stmt();
	}
	expect(Tok_END_REPEAT, false, "repeat_stmt");
	expect(Tok_Semi, false, "repeat_stmt");
}

void Parser::repeat_control() {
	if( FIRST_increment_control(la.d_type) ) {
		increment_control();
	}
	if( FIRST_while_control(la.d_type) ) {
		while_control();
	}
	if( FIRST_until_control(la.d_type) ) {
		until_control();
	}
}

void Parser::increment_control() {
	expect(Tok_ident, false, "increment_control");
	expect(Tok_ColonEq, false, "increment_control");
	bound_1();
	expect(Tok_TO, false, "increment_control");
	bound_2();
	if( la.d_type == Tok_BY ) {
		expect(Tok_BY, false, "increment_control");
		numeric_expression();
	}
}

void Parser::while_control() {
	expect(Tok_WHILE, false, "while_control");
	expression();
}

void Parser::until_control() {
	expect(Tok_UNTIL, false, "until_control");
	expression();
}

void Parser::return_stmt() {
	expect(Tok_RETURN, false, "return_stmt");
	if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "return_stmt");
		expression();
		expect(Tok_Rpar, false, "return_stmt");
	}
	expect(Tok_Semi, false, "return_stmt");
}

void Parser::skip_stmt() {
	expect(Tok_SKIP, false, "skip_stmt");
	expect(Tok_Semi, false, "skip_stmt");
}

void Parser::expression() {
	and_expression();
	while( la.d_type == Tok_OR ) {
		expect(Tok_OR, false, "expression");
		and_expression();
	}
}

void Parser::and_expression() {
	rel_expression();
	while( la.d_type == Tok_AND ) {
		expect(Tok_AND, false, "and_expression");
		rel_expression();
	}
}

void Parser::rel_expression() {
	simple_expression();
	if( FIRST_rel_op_extended(la.d_type) ) {
		rel_op_extended();
		simple_expression();
	}
}

void Parser::simple_expression() {
	term();
	while( FIRST_add_like_op(la.d_type) ) {
		add_like_op();
		term();
	}
}

void Parser::term() {
	factor();
	while( FIRST_multiplication_like_op(la.d_type) ) {
		multiplication_like_op();
		factor();
	}
}

void Parser::factor() {
	simple_factor();
	if( la.d_type == Tok_2Star ) {
		expect(Tok_2Star, false, "factor");
		simple_factor();
	}
}

void Parser::simple_factor() {
	if( FIRST_aggregate_initializer(la.d_type) ) {
		aggregate_initializer();
	} else if( FIRST_interval(la.d_type) ) {
		interval();
	} else if( FIRST_query_expression(la.d_type) ) {
		query_expression();
	} else if( FIRST_unary_op(la.d_type) ) {
		unary_op();
		if( la.d_type == Tok_Lpar ) {
			expect(Tok_Lpar, false, "simple_factor");
			expression();
			expect(Tok_Rpar, false, "simple_factor");
		} else if( FIRST_primary(la.d_type) ) {
			primary();
		} else
			invalid("simple_factor");
	} else if( la.d_type == Tok_Lpar ) {
		expect(Tok_Lpar, false, "simple_factor");
		expression();
		expect(Tok_Rpar, false, "simple_factor");
	} else if( FIRST_primary(la.d_type) ) {
		primary();
	} else
		invalid("simple_factor");
}

void Parser::primary() {
	if( FIRST_literal(la.d_type) ) {
		literal();
	} else if( FIRST_built_in_constant(la.d_type) ) {
		built_in_constant();
		while( FIRST_qualifier(la.d_type) ) {
			qualifier();
		}
	} else if( FIRST_built_in_function(la.d_type) ) {
		built_in_function();
		while( FIRST_qualifier(la.d_type) ) {
			qualifier();
		}
	} else if( la.d_type == Tok_ident ) {
		expect(Tok_ident, false, "primary");
		while( FIRST_qualifier(la.d_type) ) {
			qualifier();
		}
	} else
		invalid("primary");
}

void Parser::actual_parameter_list() {
	expect(Tok_Lpar, false, "actual_parameter_list");
	if( FIRST_expression(la.d_type) ) {
		expression();
		while( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "actual_parameter_list");
			expression();
		}
	}
	expect(Tok_Rpar, false, "actual_parameter_list");
}

void Parser::qualifier() {
	if( FIRST_attribute_qualifier(la.d_type) ) {
		attribute_qualifier();
	} else if( FIRST_group_qualifier(la.d_type) ) {
		group_qualifier();
	} else if( FIRST_index_qualifier(la.d_type) ) {
		index_qualifier();
	} else if( FIRST_actual_parameter_list(la.d_type) ) {
		actual_parameter_list();
	} else
		invalid("qualifier");
}

void Parser::attribute_qualifier() {
	expect(Tok_Dot, false, "attribute_qualifier");
	expect(Tok_ident, false, "attribute_qualifier");
}

void Parser::group_qualifier() {
	expect(Tok_Bslash, false, "group_qualifier");
	expect(Tok_ident, false, "group_qualifier");
}

void Parser::index_qualifier() {
	expect(Tok_Lbrack, false, "index_qualifier");
	index_1();
	if( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "index_qualifier");
		index_2();
	}
	expect(Tok_Rbrack, false, "index_qualifier");
}

void Parser::index_1() {
	numeric_expression();
}

void Parser::index_2() {
	numeric_expression();
}

void Parser::numeric_expression() {
	simple_expression();
}

void Parser::aggregate_initializer() {
	expect(Tok_Lbrack, false, "aggregate_initializer");
	if( FIRST_element(la.d_type) ) {
		element();
		while( la.d_type == Tok_Comma ) {
			expect(Tok_Comma, false, "aggregate_initializer");
			element();
		}
	}
	expect(Tok_Rbrack, false, "aggregate_initializer");
}

void Parser::element() {
	expression();
	if( la.d_type == Tok_Colon ) {
		expect(Tok_Colon, false, "element");
		repetition();
	}
}

void Parser::repetition() {
	numeric_expression();
}

void Parser::interval() {
	expect(Tok_Lbrace, false, "interval");
	simple_expression();
	interval_op();
	simple_expression();
	interval_op();
	simple_expression();
	expect(Tok_Rbrace, false, "interval");
}

void Parser::interval_op() {
	if( la.d_type == Tok_Lt ) {
		expect(Tok_Lt, false, "interval_op");
	} else if( la.d_type == Tok_Leq ) {
		expect(Tok_Leq, false, "interval_op");
	} else
		invalid("interval_op");
}

void Parser::query_expression() {
	expect(Tok_QUERY, false, "query_expression");
	expect(Tok_Lpar, false, "query_expression");
	expect(Tok_ident, false, "query_expression");
	expect(Tok_LtStar, false, "query_expression");
	simple_expression();
	expect(Tok_Bar, false, "query_expression");
	expression();
	expect(Tok_Rpar, false, "query_expression");
}

void Parser::rel_op_extended() {
	if( FIRST_rel_op(la.d_type) ) {
		rel_op();
	} else if( la.d_type == Tok_IN ) {
		expect(Tok_IN, false, "rel_op_extended");
	} else if( la.d_type == Tok_LIKE ) {
		expect(Tok_LIKE, false, "rel_op_extended");
	} else
		invalid("rel_op_extended");
}

void Parser::rel_op() {
	if( la.d_type == Tok_Lt ) {
		expect(Tok_Lt, false, "rel_op");
	} else if( la.d_type == Tok_Gt ) {
		expect(Tok_Gt, false, "rel_op");
	} else if( la.d_type == Tok_Leq ) {
		expect(Tok_Leq, false, "rel_op");
	} else if( la.d_type == Tok_Geq ) {
		expect(Tok_Geq, false, "rel_op");
	} else if( la.d_type == Tok_LtGt ) {
		expect(Tok_LtGt, false, "rel_op");
	} else if( la.d_type == Tok_Eq ) {
		expect(Tok_Eq, false, "rel_op");
	} else if( la.d_type == Tok_ColonLtGtColon ) {
		expect(Tok_ColonLtGtColon, false, "rel_op");
	} else if( la.d_type == Tok_ColonEqColon ) {
		expect(Tok_ColonEqColon, false, "rel_op");
	} else
		invalid("rel_op");
}

void Parser::add_like_op() {
	if( la.d_type == Tok_Plus ) {
		expect(Tok_Plus, false, "add_like_op");
	} else if( la.d_type == Tok_Minus ) {
		expect(Tok_Minus, false, "add_like_op");
	} else if( la.d_type == Tok_XOR ) {
		expect(Tok_XOR, false, "add_like_op");
	} else
		invalid("add_like_op");
}

void Parser::multiplication_like_op() {
	if( la.d_type == Tok_Star ) {
		expect(Tok_Star, false, "multiplication_like_op");
	} else if( la.d_type == Tok_Slash ) {
		expect(Tok_Slash, false, "multiplication_like_op");
	} else if( la.d_type == Tok_DIV ) {
		expect(Tok_DIV, false, "multiplication_like_op");
	} else if( la.d_type == Tok_MOD ) {
		expect(Tok_MOD, false, "multiplication_like_op");
	} else if( la.d_type == Tok_2Bar ) {
		expect(Tok_2Bar, false, "multiplication_like_op");
	} else
		invalid("multiplication_like_op");
}

void Parser::unary_op() {
	if( la.d_type == Tok_Plus ) {
		expect(Tok_Plus, false, "unary_op");
	} else if( la.d_type == Tok_Minus ) {
		expect(Tok_Minus, false, "unary_op");
	} else if( la.d_type == Tok_NOT ) {
		expect(Tok_NOT, false, "unary_op");
	} else
		invalid("unary_op");
}

void Parser::built_in_constant() {
	if( la.d_type == Tok_CONST_E ) {
		expect(Tok_CONST_E, false, "built_in_constant");
	} else if( la.d_type == Tok_PI ) {
		expect(Tok_PI, false, "built_in_constant");
	} else if( la.d_type == Tok_SELF ) {
		expect(Tok_SELF, false, "built_in_constant");
	} else if( la.d_type == Tok_Qmark ) {
		expect(Tok_Qmark, false, "built_in_constant");
	} else
		invalid("built_in_constant");
}

void Parser::built_in_function() {
	if( la.d_type == Tok_ABS ) {
		expect(Tok_ABS, false, "built_in_function");
	} else if( la.d_type == Tok_ACOS ) {
		expect(Tok_ACOS, false, "built_in_function");
	} else if( la.d_type == Tok_ASIN ) {
		expect(Tok_ASIN, false, "built_in_function");
	} else if( la.d_type == Tok_ATAN ) {
		expect(Tok_ATAN, false, "built_in_function");
	} else if( la.d_type == Tok_BLENGTH ) {
		expect(Tok_BLENGTH, false, "built_in_function");
	} else if( la.d_type == Tok_COS ) {
		expect(Tok_COS, false, "built_in_function");
	} else if( la.d_type == Tok_EXISTS ) {
		expect(Tok_EXISTS, false, "built_in_function");
	} else if( la.d_type == Tok_EXP ) {
		expect(Tok_EXP, false, "built_in_function");
	} else if( la.d_type == Tok_FORMAT ) {
		expect(Tok_FORMAT, false, "built_in_function");
	} else if( la.d_type == Tok_HIBOUND ) {
		expect(Tok_HIBOUND, false, "built_in_function");
	} else if( la.d_type == Tok_HIINDEX ) {
		expect(Tok_HIINDEX, false, "built_in_function");
	} else if( la.d_type == Tok_LENGTH ) {
		expect(Tok_LENGTH, false, "built_in_function");
	} else if( la.d_type == Tok_LOBOUND ) {
		expect(Tok_LOBOUND, false, "built_in_function");
	} else if( la.d_type == Tok_LOINDEX ) {
		expect(Tok_LOINDEX, false, "built_in_function");
	} else if( la.d_type == Tok_LOG ) {
		expect(Tok_LOG, false, "built_in_function");
	} else if( la.d_type == Tok_LOG2 ) {
		expect(Tok_LOG2, false, "built_in_function");
	} else if( la.d_type == Tok_LOG10 ) {
		expect(Tok_LOG10, false, "built_in_function");
	} else if( la.d_type == Tok_NVL ) {
		expect(Tok_NVL, false, "built_in_function");
	} else if( la.d_type == Tok_ODD ) {
		expect(Tok_ODD, false, "built_in_function");
	} else if( la.d_type == Tok_ROLESOF ) {
		expect(Tok_ROLESOF, false, "built_in_function");
	} else if( la.d_type == Tok_SIN ) {
		expect(Tok_SIN, false, "built_in_function");
	} else if( la.d_type == Tok_SIZEOF ) {
		expect(Tok_SIZEOF, false, "built_in_function");
	} else if( la.d_type == Tok_SQRT ) {
		expect(Tok_SQRT, false, "built_in_function");
	} else if( la.d_type == Tok_TAN ) {
		expect(Tok_TAN, false, "built_in_function");
	} else if( la.d_type == Tok_TYPEOF ) {
		expect(Tok_TYPEOF, false, "built_in_function");
	} else if( la.d_type == Tok_USEDIN ) {
		expect(Tok_USEDIN, false, "built_in_function");
	} else if( la.d_type == Tok_VALUE ) {
		expect(Tok_VALUE, false, "built_in_function");
	} else if( la.d_type == Tok_VALUE_IN ) {
		expect(Tok_VALUE_IN, false, "built_in_function");
	} else if( la.d_type == Tok_VALUE_UNIQUE ) {
		expect(Tok_VALUE_UNIQUE, false, "built_in_function");
	} else
		invalid("built_in_function");
}

void Parser::built_in_procedure() {
	if( la.d_type == Tok_INSERT ) {
		expect(Tok_INSERT, false, "built_in_procedure");
	} else if( la.d_type == Tok_REMOVE ) {
		expect(Tok_REMOVE, false, "built_in_procedure");
	} else
		invalid("built_in_procedure");
}

void Parser::where_clause() {
	expect(Tok_WHERE, false, "where_clause");
	domain_rule();
	expect(Tok_Semi, false, "where_clause");
	while( FIRST_domain_rule(la.d_type) ) {
		domain_rule();
		expect(Tok_Semi, false, "where_clause");
	}
}

void Parser::domain_rule() {
	if( ( peek(1).d_type == Tok_ident && peek(2).d_type == Tok_Colon )  ) {
		expect(Tok_ident, false, "domain_rule");
		expect(Tok_Colon, false, "domain_rule");
	}
	expression();
}

void Parser::string_literal() {
	if( la.d_type == Tok_simple_string_literal ) {
		expect(Tok_simple_string_literal, false, "string_literal");
	} else if( la.d_type == Tok_encoded_string_literal ) {
		expect(Tok_encoded_string_literal, false, "string_literal");
	} else
		invalid("string_literal");
}

void Parser::literal() {
	if( la.d_type == Tok_binary_literal ) {
		expect(Tok_binary_literal, false, "literal");
	} else if( FIRST_logical_literal(la.d_type) ) {
		logical_literal();
	} else if( la.d_type == Tok_real_literal ) {
		expect(Tok_real_literal, false, "literal");
	} else if( la.d_type == Tok_integer_literal ) {
		expect(Tok_integer_literal, false, "literal");
	} else if( FIRST_string_literal(la.d_type) ) {
		string_literal();
	} else
		invalid("literal");
}

void Parser::logical_literal() {
	if( la.d_type == Tok_FALSE ) {
		expect(Tok_FALSE, false, "logical_literal");
	} else if( la.d_type == Tok_TRUE ) {
		expect(Tok_TRUE, false, "logical_literal");
	} else if( la.d_type == Tok_UNKNOWN ) {
		expect(Tok_UNKNOWN, false, "logical_literal");
	} else
		invalid("logical_literal");
}

