#ifndef __EXP_PARSER__
#define __EXP_PARSER__
// This file was automatically generated by EbnfStudio; don't modify it!

#include <Express/ExpToken.h>
#include <QList>

namespace Exp {

	class Scanner {
	public:
		virtual Token next() = 0;
		virtual Token peek(int offset) = 0;
	};

	class Parser {
	public:
		Parser(Scanner* s):scanner(s) {}
		void RunParser();
		struct Error {
		    QString msg;
		    int row, col;
		    QString path;
		    Error( const QString& m, int r, int c, const QString& p):msg(m),row(r),col(c),path(p){}
		};
		QList<Error> errors;
	protected:
		void syntax();
		void schema_decl();
		void schema_body();
		void interface_specification();
		void reference_clause();
		void use_clause();
		void resource_or_rename();
		void named_type_or_rename();
		void declaration();
		void constant_decl();
		void constant_body();
		void entity_decl();
		void entity_head();
		void subsuper();
		void supertype_constraint();
		void subtype_constraint();
		void subtype_declaration();
		void supertype_expression();
		void supertype_factor();
		void supertype_term();
		void one_of();
		void entity_body();
		void explicit_attr();
		void attribute_decl();
		void redeclared_attribute();
		void qualified_attribute();
		void derive_clause();
		void derived_attr();
		void inverse_clause();
		void inverse_attr();
		void unique_clause();
		void unique_rule();
		void referenced_attribute();
		void type_decl();
		void underlying_type();
		void concrete_types();
		void constructed_types();
		void enumeration_items();
		void enumeration_extension();
		void select_list();
		void select_extension();
		void parameter_type();
		void generalized_types();
		void named_types();
		void simple_types();
		void binary_type();
		void boolean_type();
		void integer_type();
		void logical_type();
		void number_type();
		void real_type();
		void string_type();
		void width_spec();
		void aggregation_types();
		void array_type();
		void bag_type();
		void list_type();
		void set_type();
		void bound_spec();
		void bound_1();
		void bound_2();
		void instantiable_type();
		void general_aggregation_types();
		void general_array_type();
		void general_bag_type();
		void general_list_type();
		void general_set_type();
		void aggregate_type();
		void type_label();
		void generic_entity_type();
		void generic_type();
		void subtype_constraint_decl();
		void subtype_constraint_head();
		void subtype_constraint_body();
		void abstract_supertype();
		void total_over();
		void function_decl();
		void function_head();
		void procedure_decl();
		void procedure_head();
		void formal_parameter();
		void algorithm_head();
		void local_decl();
		void local_variable();
		void rule_decl();
		void rule_head();
		void stmt();
		void null_stmt();
		void assignOrCall_();
		void alias_stmt();
		void case_stmt();
		void case_action();
		void case_label();
		void compound_stmt();
		void escape_stmt();
		void if_stmt();
		void repeat_stmt();
		void repeat_control();
		void increment_control();
		void while_control();
		void until_control();
		void return_stmt();
		void skip_stmt();
		void expression();
		void and_expression();
		void rel_expression();
		void simple_expression();
		void term();
		void factor();
		void simple_factor();
		void primary();
		void actual_parameter_list();
		void qualifier();
		void attribute_qualifier();
		void group_qualifier();
		void index_qualifier();
		void index_1();
		void index_2();
		void numeric_expression();
		void aggregate_initializer();
		void element();
		void repetition();
		void interval();
		void interval_op();
		void query_expression();
		void rel_op_extended();
		void rel_op();
		void add_like_op();
		void multiplication_like_op();
		void unary_op();
		void built_in_constant();
		void built_in_function();
		void built_in_procedure();
		void where_clause();
		void domain_rule();
		void string_literal();
		void literal();
		void logical_literal();
	protected:
		Token cur;
		Token la;
		Scanner* scanner;
		void next();
		Token peek(int off);
		void invalid(const char* what);
		bool expect(int tt, bool pkw, const char* where);
	};
}
#endif // include
