// This file was automatically generated by EbnfStudio; don't modify it!
#include "ExpTokenType.h"

namespace Exp {
	const char* tokenTypeString( int r ) {
		switch(r) {
			case Tok_Invalid: return "<invalid>";
			case Tok_Lpar: return "(";
			case Tok_Latt: return "(*";
			case Tok_Rpar: return ")";
			case Tok_Star: return "*";
			case Tok_Ratt: return "*)";
			case Tok_2Star: return "**";
			case Tok_Plus: return "+";
			case Tok_Comma: return ",";
			case Tok_Minus: return "-";
			case Tok_2Minus: return "--";
			case Tok_Dot: return ".";
			case Tok_Slash: return "/";
			case Tok_Colon: return ":";
			case Tok_ColonLtGtColon: return ":<>:";
			case Tok_ColonEq: return ":=";
			case Tok_ColonEqColon: return ":=:";
			case Tok_Semi: return ";";
			case Tok_Lt: return "<";
			case Tok_LtStar: return "<*";
			case Tok_Leq: return "<=";
			case Tok_LtGt: return "<>";
			case Tok_Eq: return "=";
			case Tok_Gt: return ">";
			case Tok_Geq: return ">=";
			case Tok_Qmark: return "?";
			case Tok_Lbrack: return "[";
			case Tok_Bslash: return "\\";
			case Tok_Rbrack: return "]";
			case Tok_Lbrace: return "{";
			case Tok_Bar: return "|";
			case Tok_2Bar: return "||";
			case Tok_Rbrace: return "}";
			case Tok_ABS: return "ABS";
			case Tok_ABSTRACT: return "ABSTRACT";
			case Tok_ACOS: return "ACOS";
			case Tok_AGGREGATE: return "AGGREGATE";
			case Tok_ALIAS: return "ALIAS";
			case Tok_AND: return "AND";
			case Tok_ANDOR: return "ANDOR";
			case Tok_ARRAY: return "ARRAY";
			case Tok_AS: return "AS";
			case Tok_ASIN: return "ASIN";
			case Tok_ATAN: return "ATAN";
			case Tok_BAG: return "BAG";
			case Tok_BASED_ON: return "BASED_ON";
			case Tok_BEGIN: return "BEGIN";
			case Tok_BINARY: return "BINARY";
			case Tok_BLENGTH: return "BLENGTH";
			case Tok_BOOLEAN: return "BOOLEAN";
			case Tok_BY: return "BY";
			case Tok_CASE: return "CASE";
			case Tok_CONSTANT: return "CONSTANT";
			case Tok_CONST_E: return "CONST_E";
			case Tok_COS: return "COS";
			case Tok_DERIVE: return "DERIVE";
			case Tok_DIV: return "DIV";
			case Tok_ELSE: return "ELSE";
			case Tok_END: return "END";
			case Tok_END_ALIAS: return "END_ALIAS";
			case Tok_END_CASE: return "END_CASE";
			case Tok_END_CONSTANT: return "END_CONSTANT";
			case Tok_END_ENTITY: return "END_ENTITY";
			case Tok_END_FUNCTION: return "END_FUNCTION";
			case Tok_END_IF: return "END_IF";
			case Tok_END_LOCAL: return "END_LOCAL";
			case Tok_END_PROCEDURE: return "END_PROCEDURE";
			case Tok_END_REPEAT: return "END_REPEAT";
			case Tok_END_RULE: return "END_RULE";
			case Tok_END_SCHEMA: return "END_SCHEMA";
			case Tok_END_SUBTYPE_CONSTRAINT: return "END_SUBTYPE_CONSTRAINT";
			case Tok_END_TYPE: return "END_TYPE";
			case Tok_ENTITY: return "ENTITY";
			case Tok_ENUMERATION: return "ENUMERATION";
			case Tok_ESCAPE: return "ESCAPE";
			case Tok_EXISTS: return "EXISTS";
			case Tok_EXP: return "EXP";
			case Tok_EXTENSIBLE: return "EXTENSIBLE";
			case Tok_FALSE: return "FALSE";
			case Tok_FIXED: return "FIXED";
			case Tok_FOR: return "FOR";
			case Tok_FORMAT: return "FORMAT";
			case Tok_FROM: return "FROM";
			case Tok_FUNCTION: return "FUNCTION";
			case Tok_GENERIC: return "GENERIC";
			case Tok_GENERIC_ENTITY: return "GENERIC_ENTITY";
			case Tok_HIBOUND: return "HIBOUND";
			case Tok_HIINDEX: return "HIINDEX";
			case Tok_IF: return "IF";
			case Tok_IN: return "IN";
			case Tok_INSERT: return "INSERT";
			case Tok_INTEGER: return "INTEGER";
			case Tok_INVERSE: return "INVERSE";
			case Tok_LENGTH: return "LENGTH";
			case Tok_LIKE: return "LIKE";
			case Tok_LIST: return "LIST";
			case Tok_LOBOUND: return "LOBOUND";
			case Tok_LOCAL: return "LOCAL";
			case Tok_LOG: return "LOG";
			case Tok_LOG10: return "LOG10";
			case Tok_LOG2: return "LOG2";
			case Tok_LOGICAL: return "LOGICAL";
			case Tok_LOINDEX: return "LOINDEX";
			case Tok_MOD: return "MOD";
			case Tok_NOT: return "NOT";
			case Tok_NUMBER: return "NUMBER";
			case Tok_NVL: return "NVL";
			case Tok_ODD: return "ODD";
			case Tok_OF: return "OF";
			case Tok_ONEOF: return "ONEOF";
			case Tok_OPTIONAL: return "OPTIONAL";
			case Tok_OR: return "OR";
			case Tok_OTHERWISE: return "OTHERWISE";
			case Tok_PI: return "PI";
			case Tok_PROCEDURE: return "PROCEDURE";
			case Tok_QUERY: return "QUERY";
			case Tok_REAL: return "REAL";
			case Tok_REFERENCE: return "REFERENCE";
			case Tok_REMOVE: return "REMOVE";
			case Tok_RENAMED: return "RENAMED";
			case Tok_REPEAT: return "REPEAT";
			case Tok_RETURN: return "RETURN";
			case Tok_ROLESOF: return "ROLESOF";
			case Tok_RULE: return "RULE";
			case Tok_SCHEMA: return "SCHEMA";
			case Tok_SELECT: return "SELECT";
			case Tok_SELF: return "SELF";
			case Tok_SET: return "SET";
			case Tok_SIN: return "SIN";
			case Tok_SIZEOF: return "SIZEOF";
			case Tok_SKIP: return "SKIP";
			case Tok_SQRT: return "SQRT";
			case Tok_STRING: return "STRING";
			case Tok_SUBTYPE: return "SUBTYPE";
			case Tok_SUBTYPE_CONSTRAINT: return "SUBTYPE_CONSTRAINT";
			case Tok_SUPERTYPE: return "SUPERTYPE";
			case Tok_TAN: return "TAN";
			case Tok_THEN: return "THEN";
			case Tok_TO: return "TO";
			case Tok_TOTAL_OVER: return "TOTAL_OVER";
			case Tok_TRUE: return "TRUE";
			case Tok_TYPE: return "TYPE";
			case Tok_TYPEOF: return "TYPEOF";
			case Tok_UNIQUE: return "UNIQUE";
			case Tok_UNKNOWN: return "UNKNOWN";
			case Tok_UNTIL: return "UNTIL";
			case Tok_USE: return "USE";
			case Tok_USEDIN: return "USEDIN";
			case Tok_VALUE: return "VALUE";
			case Tok_VALUE_IN: return "VALUE_IN";
			case Tok_VALUE_UNIQUE: return "VALUE_UNIQUE";
			case Tok_VAR: return "VAR";
			case Tok_WHERE: return "WHERE";
			case Tok_WHILE: return "WHILE";
			case Tok_WITH: return "WITH";
			case Tok_XOR: return "XOR";
			case Tok_ident: return "ident";
			case Tok_integer_literal: return "integer_literal";
			case Tok_real_literal: return "real_literal";
			case Tok_simple_string_literal: return "simple_string_literal";
			case Tok_encoded_string_literal: return "encoded_string_literal";
			case Tok_binary_literal: return "binary_literal";
			case Tok_Comment: return "Comment";
			case Tok_Eof: return "<eof>";
			default: return "";
		}
	}
	const char* tokenTypeName( int r ) {
		switch(r) {
			case Tok_Invalid: return "Tok_Invalid";
			case Tok_Lpar: return "Tok_Lpar";
			case Tok_Latt: return "Tok_Latt";
			case Tok_Rpar: return "Tok_Rpar";
			case Tok_Star: return "Tok_Star";
			case Tok_Ratt: return "Tok_Ratt";
			case Tok_2Star: return "Tok_2Star";
			case Tok_Plus: return "Tok_Plus";
			case Tok_Comma: return "Tok_Comma";
			case Tok_Minus: return "Tok_Minus";
			case Tok_2Minus: return "Tok_2Minus";
			case Tok_Dot: return "Tok_Dot";
			case Tok_Slash: return "Tok_Slash";
			case Tok_Colon: return "Tok_Colon";
			case Tok_ColonLtGtColon: return "Tok_ColonLtGtColon";
			case Tok_ColonEq: return "Tok_ColonEq";
			case Tok_ColonEqColon: return "Tok_ColonEqColon";
			case Tok_Semi: return "Tok_Semi";
			case Tok_Lt: return "Tok_Lt";
			case Tok_LtStar: return "Tok_LtStar";
			case Tok_Leq: return "Tok_Leq";
			case Tok_LtGt: return "Tok_LtGt";
			case Tok_Eq: return "Tok_Eq";
			case Tok_Gt: return "Tok_Gt";
			case Tok_Geq: return "Tok_Geq";
			case Tok_Qmark: return "Tok_Qmark";
			case Tok_Lbrack: return "Tok_Lbrack";
			case Tok_Bslash: return "Tok_Bslash";
			case Tok_Rbrack: return "Tok_Rbrack";
			case Tok_Lbrace: return "Tok_Lbrace";
			case Tok_Bar: return "Tok_Bar";
			case Tok_2Bar: return "Tok_2Bar";
			case Tok_Rbrace: return "Tok_Rbrace";
			case Tok_ABS: return "Tok_ABS";
			case Tok_ABSTRACT: return "Tok_ABSTRACT";
			case Tok_ACOS: return "Tok_ACOS";
			case Tok_AGGREGATE: return "Tok_AGGREGATE";
			case Tok_ALIAS: return "Tok_ALIAS";
			case Tok_AND: return "Tok_AND";
			case Tok_ANDOR: return "Tok_ANDOR";
			case Tok_ARRAY: return "Tok_ARRAY";
			case Tok_AS: return "Tok_AS";
			case Tok_ASIN: return "Tok_ASIN";
			case Tok_ATAN: return "Tok_ATAN";
			case Tok_BAG: return "Tok_BAG";
			case Tok_BASED_ON: return "Tok_BASED_ON";
			case Tok_BEGIN: return "Tok_BEGIN";
			case Tok_BINARY: return "Tok_BINARY";
			case Tok_BLENGTH: return "Tok_BLENGTH";
			case Tok_BOOLEAN: return "Tok_BOOLEAN";
			case Tok_BY: return "Tok_BY";
			case Tok_CASE: return "Tok_CASE";
			case Tok_CONSTANT: return "Tok_CONSTANT";
			case Tok_CONST_E: return "Tok_CONST_E";
			case Tok_COS: return "Tok_COS";
			case Tok_DERIVE: return "Tok_DERIVE";
			case Tok_DIV: return "Tok_DIV";
			case Tok_ELSE: return "Tok_ELSE";
			case Tok_END: return "Tok_END";
			case Tok_END_ALIAS: return "Tok_END_ALIAS";
			case Tok_END_CASE: return "Tok_END_CASE";
			case Tok_END_CONSTANT: return "Tok_END_CONSTANT";
			case Tok_END_ENTITY: return "Tok_END_ENTITY";
			case Tok_END_FUNCTION: return "Tok_END_FUNCTION";
			case Tok_END_IF: return "Tok_END_IF";
			case Tok_END_LOCAL: return "Tok_END_LOCAL";
			case Tok_END_PROCEDURE: return "Tok_END_PROCEDURE";
			case Tok_END_REPEAT: return "Tok_END_REPEAT";
			case Tok_END_RULE: return "Tok_END_RULE";
			case Tok_END_SCHEMA: return "Tok_END_SCHEMA";
			case Tok_END_SUBTYPE_CONSTRAINT: return "Tok_END_SUBTYPE_CONSTRAINT";
			case Tok_END_TYPE: return "Tok_END_TYPE";
			case Tok_ENTITY: return "Tok_ENTITY";
			case Tok_ENUMERATION: return "Tok_ENUMERATION";
			case Tok_ESCAPE: return "Tok_ESCAPE";
			case Tok_EXISTS: return "Tok_EXISTS";
			case Tok_EXP: return "Tok_EXP";
			case Tok_EXTENSIBLE: return "Tok_EXTENSIBLE";
			case Tok_FALSE: return "Tok_FALSE";
			case Tok_FIXED: return "Tok_FIXED";
			case Tok_FOR: return "Tok_FOR";
			case Tok_FORMAT: return "Tok_FORMAT";
			case Tok_FROM: return "Tok_FROM";
			case Tok_FUNCTION: return "Tok_FUNCTION";
			case Tok_GENERIC: return "Tok_GENERIC";
			case Tok_GENERIC_ENTITY: return "Tok_GENERIC_ENTITY";
			case Tok_HIBOUND: return "Tok_HIBOUND";
			case Tok_HIINDEX: return "Tok_HIINDEX";
			case Tok_IF: return "Tok_IF";
			case Tok_IN: return "Tok_IN";
			case Tok_INSERT: return "Tok_INSERT";
			case Tok_INTEGER: return "Tok_INTEGER";
			case Tok_INVERSE: return "Tok_INVERSE";
			case Tok_LENGTH: return "Tok_LENGTH";
			case Tok_LIKE: return "Tok_LIKE";
			case Tok_LIST: return "Tok_LIST";
			case Tok_LOBOUND: return "Tok_LOBOUND";
			case Tok_LOCAL: return "Tok_LOCAL";
			case Tok_LOG: return "Tok_LOG";
			case Tok_LOG10: return "Tok_LOG10";
			case Tok_LOG2: return "Tok_LOG2";
			case Tok_LOGICAL: return "Tok_LOGICAL";
			case Tok_LOINDEX: return "Tok_LOINDEX";
			case Tok_MOD: return "Tok_MOD";
			case Tok_NOT: return "Tok_NOT";
			case Tok_NUMBER: return "Tok_NUMBER";
			case Tok_NVL: return "Tok_NVL";
			case Tok_ODD: return "Tok_ODD";
			case Tok_OF: return "Tok_OF";
			case Tok_ONEOF: return "Tok_ONEOF";
			case Tok_OPTIONAL: return "Tok_OPTIONAL";
			case Tok_OR: return "Tok_OR";
			case Tok_OTHERWISE: return "Tok_OTHERWISE";
			case Tok_PI: return "Tok_PI";
			case Tok_PROCEDURE: return "Tok_PROCEDURE";
			case Tok_QUERY: return "Tok_QUERY";
			case Tok_REAL: return "Tok_REAL";
			case Tok_REFERENCE: return "Tok_REFERENCE";
			case Tok_REMOVE: return "Tok_REMOVE";
			case Tok_RENAMED: return "Tok_RENAMED";
			case Tok_REPEAT: return "Tok_REPEAT";
			case Tok_RETURN: return "Tok_RETURN";
			case Tok_ROLESOF: return "Tok_ROLESOF";
			case Tok_RULE: return "Tok_RULE";
			case Tok_SCHEMA: return "Tok_SCHEMA";
			case Tok_SELECT: return "Tok_SELECT";
			case Tok_SELF: return "Tok_SELF";
			case Tok_SET: return "Tok_SET";
			case Tok_SIN: return "Tok_SIN";
			case Tok_SIZEOF: return "Tok_SIZEOF";
			case Tok_SKIP: return "Tok_SKIP";
			case Tok_SQRT: return "Tok_SQRT";
			case Tok_STRING: return "Tok_STRING";
			case Tok_SUBTYPE: return "Tok_SUBTYPE";
			case Tok_SUBTYPE_CONSTRAINT: return "Tok_SUBTYPE_CONSTRAINT";
			case Tok_SUPERTYPE: return "Tok_SUPERTYPE";
			case Tok_TAN: return "Tok_TAN";
			case Tok_THEN: return "Tok_THEN";
			case Tok_TO: return "Tok_TO";
			case Tok_TOTAL_OVER: return "Tok_TOTAL_OVER";
			case Tok_TRUE: return "Tok_TRUE";
			case Tok_TYPE: return "Tok_TYPE";
			case Tok_TYPEOF: return "Tok_TYPEOF";
			case Tok_UNIQUE: return "Tok_UNIQUE";
			case Tok_UNKNOWN: return "Tok_UNKNOWN";
			case Tok_UNTIL: return "Tok_UNTIL";
			case Tok_USE: return "Tok_USE";
			case Tok_USEDIN: return "Tok_USEDIN";
			case Tok_VALUE: return "Tok_VALUE";
			case Tok_VALUE_IN: return "Tok_VALUE_IN";
			case Tok_VALUE_UNIQUE: return "Tok_VALUE_UNIQUE";
			case Tok_VAR: return "Tok_VAR";
			case Tok_WHERE: return "Tok_WHERE";
			case Tok_WHILE: return "Tok_WHILE";
			case Tok_WITH: return "Tok_WITH";
			case Tok_XOR: return "Tok_XOR";
			case Tok_ident: return "Tok_ident";
			case Tok_integer_literal: return "Tok_integer_literal";
			case Tok_real_literal: return "Tok_real_literal";
			case Tok_simple_string_literal: return "Tok_simple_string_literal";
			case Tok_encoded_string_literal: return "Tok_encoded_string_literal";
			case Tok_binary_literal: return "Tok_binary_literal";
			case Tok_Comment: return "Tok_Comment";
			case Tok_Eof: return "Tok_Eof";
			default: return "";
		}
	}
	bool tokenTypeIsLiteral( int r ) {
		return r > TT_Literals && r < TT_Keywords;
	}
	bool tokenTypeIsKeyword( int r ) {
		return r > TT_Keywords && r < TT_Specials;
	}
	bool tokenTypeIsSpecial( int r ) {
		return r > TT_Specials && r < TT_Max;
	}
	static inline char at( const char* str, quint32 len, int i ){
		return ( i < len ? str[i] : 0 );
	}
	TokenType tokenTypeFromString( const QByteArray& str, int* pos ) {
		return tokenTypeFromString(str.constData(),str.size(),pos);
	}
	TokenType tokenTypeFromString( const char* str, quint32 len, int* pos ) {
		int i = ( pos != 0 ? *pos: 0 );
		TokenType res = Tok_Invalid;
		switch( at(str,len,i) ){
		case '(':
			if( at(str,len,i+1) == '*' ){
				res = Tok_Latt; i += 2;
			} else {
				res = Tok_Lpar; i += 1;
			}
			break;
		case ')':
			res = Tok_Rpar; i += 1;
			break;
		case '*':
			switch( at(str,len,i+1) ){
			case ')':
				res = Tok_Ratt; i += 2;
				break;
			case '*':
				res = Tok_2Star; i += 2;
				break;
			default:
				res = Tok_Star; i += 1;
				break;
			}
			break;
		case '+':
			res = Tok_Plus; i += 1;
			break;
		case ',':
			res = Tok_Comma; i += 1;
			break;
		case '-':
			if( at(str,len,i+1) == '-' ){
				res = Tok_2Minus; i += 2;
			} else {
				res = Tok_Minus; i += 1;
			}
			break;
		case '.':
			res = Tok_Dot; i += 1;
			break;
		case '/':
			res = Tok_Slash; i += 1;
			break;
		case ':':
			switch( at(str,len,i+1) ){
			case '<':
				if( at(str,len,i+2) == '>' ){
					if( at(str,len,i+3) == ':' ){
						res = Tok_ColonLtGtColon; i += 4;
					}
				}
				break;
			case '=':
				if( at(str,len,i+2) == ':' ){
					res = Tok_ColonEqColon; i += 3;
				} else {
					res = Tok_ColonEq; i += 2;
				}
				break;
			default:
				res = Tok_Colon; i += 1;
				break;
			}
			break;
		case ';':
			res = Tok_Semi; i += 1;
			break;
		case '<':
			switch( at(str,len,i+1) ){
			case '*':
				res = Tok_LtStar; i += 2;
				break;
			case '=':
				res = Tok_Leq; i += 2;
				break;
			case '>':
				res = Tok_LtGt; i += 2;
				break;
			default:
				res = Tok_Lt; i += 1;
				break;
			}
			break;
		case '=':
			res = Tok_Eq; i += 1;
			break;
		case '>':
			if( at(str,len,i+1) == '=' ){
				res = Tok_Geq; i += 2;
			} else {
				res = Tok_Gt; i += 1;
			}
			break;
		case '?':
			res = Tok_Qmark; i += 1;
			break;
		case 'A':
			switch( at(str,len,i+1) ){
			case 'B':
				if( at(str,len,i+2) == 'S' ){
					if( at(str,len,i+3) == 'T' ){
						if( at(str,len,i+4) == 'R' ){
							if( at(str,len,i+5) == 'A' ){
								if( at(str,len,i+6) == 'C' ){
									if( at(str,len,i+7) == 'T' ){
										res = Tok_ABSTRACT; i += 8;
									}
								}
							}
						}
					} else {
						res = Tok_ABS; i += 3;
					}
				}
				break;
			case 'C':
				if( at(str,len,i+2) == 'O' ){
					if( at(str,len,i+3) == 'S' ){
						res = Tok_ACOS; i += 4;
					}
				}
				break;
			case 'G':
				if( at(str,len,i+2) == 'G' ){
					if( at(str,len,i+3) == 'R' ){
						if( at(str,len,i+4) == 'E' ){
							if( at(str,len,i+5) == 'G' ){
								if( at(str,len,i+6) == 'A' ){
									if( at(str,len,i+7) == 'T' ){
										if( at(str,len,i+8) == 'E' ){
											res = Tok_AGGREGATE; i += 9;
										}
									}
								}
							}
						}
					}
				}
				break;
			case 'L':
				if( at(str,len,i+2) == 'I' ){
					if( at(str,len,i+3) == 'A' ){
						if( at(str,len,i+4) == 'S' ){
							res = Tok_ALIAS; i += 5;
						}
					}
				}
				break;
			case 'N':
				if( at(str,len,i+2) == 'D' ){
					if( at(str,len,i+3) == 'O' ){
						if( at(str,len,i+4) == 'R' ){
							res = Tok_ANDOR; i += 5;
						}
					} else {
						res = Tok_AND; i += 3;
					}
				}
				break;
			case 'R':
				if( at(str,len,i+2) == 'R' ){
					if( at(str,len,i+3) == 'A' ){
						if( at(str,len,i+4) == 'Y' ){
							res = Tok_ARRAY; i += 5;
						}
					}
				}
				break;
			case 'S':
				if( at(str,len,i+2) == 'I' ){
					if( at(str,len,i+3) == 'N' ){
						res = Tok_ASIN; i += 4;
					}
				} else {
					res = Tok_AS; i += 2;
				}
				break;
			case 'T':
				if( at(str,len,i+2) == 'A' ){
					if( at(str,len,i+3) == 'N' ){
						res = Tok_ATAN; i += 4;
					}
				}
				break;
			}
			break;
		case 'B':
			switch( at(str,len,i+1) ){
			case 'A':
				switch( at(str,len,i+2) ){
				case 'G':
					res = Tok_BAG; i += 3;
					break;
				case 'S':
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'D' ){
							if( at(str,len,i+5) == '_' ){
								if( at(str,len,i+6) == 'O' ){
									if( at(str,len,i+7) == 'N' ){
										res = Tok_BASED_ON; i += 8;
									}
								}
							}
						}
					}
					break;
				}
				break;
			case 'E':
				if( at(str,len,i+2) == 'G' ){
					if( at(str,len,i+3) == 'I' ){
						if( at(str,len,i+4) == 'N' ){
							res = Tok_BEGIN; i += 5;
						}
					}
				}
				break;
			case 'I':
				if( at(str,len,i+2) == 'N' ){
					if( at(str,len,i+3) == 'A' ){
						if( at(str,len,i+4) == 'R' ){
							if( at(str,len,i+5) == 'Y' ){
								res = Tok_BINARY; i += 6;
							}
						}
					}
				}
				break;
			case 'L':
				if( at(str,len,i+2) == 'E' ){
					if( at(str,len,i+3) == 'N' ){
						if( at(str,len,i+4) == 'G' ){
							if( at(str,len,i+5) == 'T' ){
								if( at(str,len,i+6) == 'H' ){
									res = Tok_BLENGTH; i += 7;
								}
							}
						}
					}
				}
				break;
			case 'O':
				if( at(str,len,i+2) == 'O' ){
					if( at(str,len,i+3) == 'L' ){
						if( at(str,len,i+4) == 'E' ){
							if( at(str,len,i+5) == 'A' ){
								if( at(str,len,i+6) == 'N' ){
									res = Tok_BOOLEAN; i += 7;
								}
							}
						}
					}
				}
				break;
			case 'Y':
				res = Tok_BY; i += 2;
				break;
			}
			break;
		case 'C':
			switch( at(str,len,i+1) ){
			case 'A':
				if( at(str,len,i+2) == 'S' ){
					if( at(str,len,i+3) == 'E' ){
						res = Tok_CASE; i += 4;
					}
				}
				break;
			case 'O':
				switch( at(str,len,i+2) ){
				case 'N':
					if( at(str,len,i+3) == 'S' ){
						if( at(str,len,i+4) == 'T' ){
							switch( at(str,len,i+5) ){
							case 'A':
								if( at(str,len,i+6) == 'N' ){
									if( at(str,len,i+7) == 'T' ){
										res = Tok_CONSTANT; i += 8;
									}
								}
								break;
							case '_':
								if( at(str,len,i+6) == 'E' ){
									res = Tok_CONST_E; i += 7;
								}
								break;
							}
						}
					}
					break;
				case 'S':
					res = Tok_COS; i += 3;
					break;
				}
				break;
			}
			break;
		case 'D':
			switch( at(str,len,i+1) ){
			case 'E':
				if( at(str,len,i+2) == 'R' ){
					if( at(str,len,i+3) == 'I' ){
						if( at(str,len,i+4) == 'V' ){
							if( at(str,len,i+5) == 'E' ){
								res = Tok_DERIVE; i += 6;
							}
						}
					}
				}
				break;
			case 'I':
				if( at(str,len,i+2) == 'V' ){
					res = Tok_DIV; i += 3;
				}
				break;
			}
			break;
		case 'E':
			switch( at(str,len,i+1) ){
			case 'L':
				if( at(str,len,i+2) == 'S' ){
					if( at(str,len,i+3) == 'E' ){
						res = Tok_ELSE; i += 4;
					}
				}
				break;
			case 'N':
				switch( at(str,len,i+2) ){
				case 'D':
					if( at(str,len,i+3) == '_' ){
						switch( at(str,len,i+4) ){
						case 'A':
							if( at(str,len,i+5) == 'L' ){
								if( at(str,len,i+6) == 'I' ){
									if( at(str,len,i+7) == 'A' ){
										if( at(str,len,i+8) == 'S' ){
											res = Tok_END_ALIAS; i += 9;
										}
									}
								}
							}
							break;
						case 'C':
							switch( at(str,len,i+5) ){
							case 'A':
								if( at(str,len,i+6) == 'S' ){
									if( at(str,len,i+7) == 'E' ){
										res = Tok_END_CASE; i += 8;
									}
								}
								break;
							case 'O':
								if( at(str,len,i+6) == 'N' ){
									if( at(str,len,i+7) == 'S' ){
										if( at(str,len,i+8) == 'T' ){
											if( at(str,len,i+9) == 'A' ){
												if( at(str,len,i+10) == 'N' ){
													if( at(str,len,i+11) == 'T' ){
														res = Tok_END_CONSTANT; i += 12;
													}
												}
											}
										}
									}
								}
								break;
							}
							break;
						case 'E':
							if( at(str,len,i+5) == 'N' ){
								if( at(str,len,i+6) == 'T' ){
									if( at(str,len,i+7) == 'I' ){
										if( at(str,len,i+8) == 'T' ){
											if( at(str,len,i+9) == 'Y' ){
												res = Tok_END_ENTITY; i += 10;
											}
										}
									}
								}
							}
							break;
						case 'F':
							if( at(str,len,i+5) == 'U' ){
								if( at(str,len,i+6) == 'N' ){
									if( at(str,len,i+7) == 'C' ){
										if( at(str,len,i+8) == 'T' ){
											if( at(str,len,i+9) == 'I' ){
												if( at(str,len,i+10) == 'O' ){
													if( at(str,len,i+11) == 'N' ){
														res = Tok_END_FUNCTION; i += 12;
													}
												}
											}
										}
									}
								}
							}
							break;
						case 'I':
							if( at(str,len,i+5) == 'F' ){
								res = Tok_END_IF; i += 6;
							}
							break;
						case 'L':
							if( at(str,len,i+5) == 'O' ){
								if( at(str,len,i+6) == 'C' ){
									if( at(str,len,i+7) == 'A' ){
										if( at(str,len,i+8) == 'L' ){
											res = Tok_END_LOCAL; i += 9;
										}
									}
								}
							}
							break;
						case 'P':
							if( at(str,len,i+5) == 'R' ){
								if( at(str,len,i+6) == 'O' ){
									if( at(str,len,i+7) == 'C' ){
										if( at(str,len,i+8) == 'E' ){
											if( at(str,len,i+9) == 'D' ){
												if( at(str,len,i+10) == 'U' ){
													if( at(str,len,i+11) == 'R' ){
														if( at(str,len,i+12) == 'E' ){
															res = Tok_END_PROCEDURE; i += 13;
														}
													}
												}
											}
										}
									}
								}
							}
							break;
						case 'R':
							switch( at(str,len,i+5) ){
							case 'E':
								if( at(str,len,i+6) == 'P' ){
									if( at(str,len,i+7) == 'E' ){
										if( at(str,len,i+8) == 'A' ){
											if( at(str,len,i+9) == 'T' ){
												res = Tok_END_REPEAT; i += 10;
											}
										}
									}
								}
								break;
							case 'U':
								if( at(str,len,i+6) == 'L' ){
									if( at(str,len,i+7) == 'E' ){
										res = Tok_END_RULE; i += 8;
									}
								}
								break;
							}
							break;
						case 'S':
							switch( at(str,len,i+5) ){
							case 'C':
								if( at(str,len,i+6) == 'H' ){
									if( at(str,len,i+7) == 'E' ){
										if( at(str,len,i+8) == 'M' ){
											if( at(str,len,i+9) == 'A' ){
												res = Tok_END_SCHEMA; i += 10;
											}
										}
									}
								}
								break;
							case 'U':
								if( at(str,len,i+6) == 'B' ){
									if( at(str,len,i+7) == 'T' ){
										if( at(str,len,i+8) == 'Y' ){
											if( at(str,len,i+9) == 'P' ){
												if( at(str,len,i+10) == 'E' ){
													if( at(str,len,i+11) == '_' ){
														if( at(str,len,i+12) == 'C' ){
															if( at(str,len,i+13) == 'O' ){
																if( at(str,len,i+14) == 'N' ){
																	if( at(str,len,i+15) == 'S' ){
																		if( at(str,len,i+16) == 'T' ){
																			if( at(str,len,i+17) == 'R' ){
																				if( at(str,len,i+18) == 'A' ){
																					if( at(str,len,i+19) == 'I' ){
																						if( at(str,len,i+20) == 'N' ){
																							if( at(str,len,i+21) == 'T' ){
																								res = Tok_END_SUBTYPE_CONSTRAINT; i += 22;
																							}
																						}
																					}
																				}
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
								break;
							}
							break;
						case 'T':
							if( at(str,len,i+5) == 'Y' ){
								if( at(str,len,i+6) == 'P' ){
									if( at(str,len,i+7) == 'E' ){
										res = Tok_END_TYPE; i += 8;
									}
								}
							}
							break;
						}
					} else {
						res = Tok_END; i += 3;
					}
					break;
				case 'T':
					if( at(str,len,i+3) == 'I' ){
						if( at(str,len,i+4) == 'T' ){
							if( at(str,len,i+5) == 'Y' ){
								res = Tok_ENTITY; i += 6;
							}
						}
					}
					break;
				case 'U':
					if( at(str,len,i+3) == 'M' ){
						if( at(str,len,i+4) == 'E' ){
							if( at(str,len,i+5) == 'R' ){
								if( at(str,len,i+6) == 'A' ){
									if( at(str,len,i+7) == 'T' ){
										if( at(str,len,i+8) == 'I' ){
											if( at(str,len,i+9) == 'O' ){
												if( at(str,len,i+10) == 'N' ){
													res = Tok_ENUMERATION; i += 11;
												}
											}
										}
									}
								}
							}
						}
					}
					break;
				}
				break;
			case 'S':
				if( at(str,len,i+2) == 'C' ){
					if( at(str,len,i+3) == 'A' ){
						if( at(str,len,i+4) == 'P' ){
							if( at(str,len,i+5) == 'E' ){
								res = Tok_ESCAPE; i += 6;
							}
						}
					}
				}
				break;
			case 'X':
				switch( at(str,len,i+2) ){
				case 'I':
					if( at(str,len,i+3) == 'S' ){
						if( at(str,len,i+4) == 'T' ){
							if( at(str,len,i+5) == 'S' ){
								res = Tok_EXISTS; i += 6;
							}
						}
					}
					break;
				case 'P':
					res = Tok_EXP; i += 3;
					break;
				case 'T':
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'N' ){
							if( at(str,len,i+5) == 'S' ){
								if( at(str,len,i+6) == 'I' ){
									if( at(str,len,i+7) == 'B' ){
										if( at(str,len,i+8) == 'L' ){
											if( at(str,len,i+9) == 'E' ){
												res = Tok_EXTENSIBLE; i += 10;
											}
										}
									}
								}
							}
						}
					}
					break;
				}
				break;
			}
			break;
		case 'F':
			switch( at(str,len,i+1) ){
			case 'A':
				if( at(str,len,i+2) == 'L' ){
					if( at(str,len,i+3) == 'S' ){
						if( at(str,len,i+4) == 'E' ){
							res = Tok_FALSE; i += 5;
						}
					}
				}
				break;
			case 'I':
				if( at(str,len,i+2) == 'X' ){
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'D' ){
							res = Tok_FIXED; i += 5;
						}
					}
				}
				break;
			case 'O':
				if( at(str,len,i+2) == 'R' ){
					if( at(str,len,i+3) == 'M' ){
						if( at(str,len,i+4) == 'A' ){
							if( at(str,len,i+5) == 'T' ){
								res = Tok_FORMAT; i += 6;
							}
						}
					} else {
						res = Tok_FOR; i += 3;
					}
				}
				break;
			case 'R':
				if( at(str,len,i+2) == 'O' ){
					if( at(str,len,i+3) == 'M' ){
						res = Tok_FROM; i += 4;
					}
				}
				break;
			case 'U':
				if( at(str,len,i+2) == 'N' ){
					if( at(str,len,i+3) == 'C' ){
						if( at(str,len,i+4) == 'T' ){
							if( at(str,len,i+5) == 'I' ){
								if( at(str,len,i+6) == 'O' ){
									if( at(str,len,i+7) == 'N' ){
										res = Tok_FUNCTION; i += 8;
									}
								}
							}
						}
					}
				}
				break;
			}
			break;
		case 'G':
			if( at(str,len,i+1) == 'E' ){
				if( at(str,len,i+2) == 'N' ){
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'R' ){
							if( at(str,len,i+5) == 'I' ){
								if( at(str,len,i+6) == 'C' ){
									if( at(str,len,i+7) == '_' ){
										if( at(str,len,i+8) == 'E' ){
											if( at(str,len,i+9) == 'N' ){
												if( at(str,len,i+10) == 'T' ){
													if( at(str,len,i+11) == 'I' ){
														if( at(str,len,i+12) == 'T' ){
															if( at(str,len,i+13) == 'Y' ){
																res = Tok_GENERIC_ENTITY; i += 14;
															}
														}
													}
												}
											}
										}
									} else {
										res = Tok_GENERIC; i += 7;
									}
								}
							}
						}
					}
				}
			}
			break;
		case 'H':
			if( at(str,len,i+1) == 'I' ){
				switch( at(str,len,i+2) ){
				case 'B':
					if( at(str,len,i+3) == 'O' ){
						if( at(str,len,i+4) == 'U' ){
							if( at(str,len,i+5) == 'N' ){
								if( at(str,len,i+6) == 'D' ){
									res = Tok_HIBOUND; i += 7;
								}
							}
						}
					}
					break;
				case 'I':
					if( at(str,len,i+3) == 'N' ){
						if( at(str,len,i+4) == 'D' ){
							if( at(str,len,i+5) == 'E' ){
								if( at(str,len,i+6) == 'X' ){
									res = Tok_HIINDEX; i += 7;
								}
							}
						}
					}
					break;
				}
			}
			break;
		case 'I':
			switch( at(str,len,i+1) ){
			case 'F':
				res = Tok_IF; i += 2;
				break;
			case 'N':
				switch( at(str,len,i+2) ){
				case 'S':
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'R' ){
							if( at(str,len,i+5) == 'T' ){
								res = Tok_INSERT; i += 6;
							}
						}
					}
					break;
				case 'T':
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'G' ){
							if( at(str,len,i+5) == 'E' ){
								if( at(str,len,i+6) == 'R' ){
									res = Tok_INTEGER; i += 7;
								}
							}
						}
					}
					break;
				case 'V':
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'R' ){
							if( at(str,len,i+5) == 'S' ){
								if( at(str,len,i+6) == 'E' ){
									res = Tok_INVERSE; i += 7;
								}
							}
						}
					}
					break;
				default:
					res = Tok_IN; i += 2;
					break;
				}
				break;
			}
			break;
		case 'L':
			switch( at(str,len,i+1) ){
			case 'E':
				if( at(str,len,i+2) == 'N' ){
					if( at(str,len,i+3) == 'G' ){
						if( at(str,len,i+4) == 'T' ){
							if( at(str,len,i+5) == 'H' ){
								res = Tok_LENGTH; i += 6;
							}
						}
					}
				}
				break;
			case 'I':
				switch( at(str,len,i+2) ){
				case 'K':
					if( at(str,len,i+3) == 'E' ){
						res = Tok_LIKE; i += 4;
					}
					break;
				case 'S':
					if( at(str,len,i+3) == 'T' ){
						res = Tok_LIST; i += 4;
					}
					break;
				}
				break;
			case 'O':
				switch( at(str,len,i+2) ){
				case 'B':
					if( at(str,len,i+3) == 'O' ){
						if( at(str,len,i+4) == 'U' ){
							if( at(str,len,i+5) == 'N' ){
								if( at(str,len,i+6) == 'D' ){
									res = Tok_LOBOUND; i += 7;
								}
							}
						}
					}
					break;
				case 'C':
					if( at(str,len,i+3) == 'A' ){
						if( at(str,len,i+4) == 'L' ){
							res = Tok_LOCAL; i += 5;
						}
					}
					break;
				case 'G':
					switch( at(str,len,i+3) ){
					case '1':
						if( at(str,len,i+4) == '0' ){
							res = Tok_LOG10; i += 5;
						}
						break;
					case '2':
						res = Tok_LOG2; i += 4;
						break;
					case 'I':
						if( at(str,len,i+4) == 'C' ){
							if( at(str,len,i+5) == 'A' ){
								if( at(str,len,i+6) == 'L' ){
									res = Tok_LOGICAL; i += 7;
								}
							}
						}
						break;
					default:
						res = Tok_LOG; i += 3;
						break;
					}
					break;
				case 'I':
					if( at(str,len,i+3) == 'N' ){
						if( at(str,len,i+4) == 'D' ){
							if( at(str,len,i+5) == 'E' ){
								if( at(str,len,i+6) == 'X' ){
									res = Tok_LOINDEX; i += 7;
								}
							}
						}
					}
					break;
				}
				break;
			}
			break;
		case 'M':
			if( at(str,len,i+1) == 'O' ){
				if( at(str,len,i+2) == 'D' ){
					res = Tok_MOD; i += 3;
				}
			}
			break;
		case 'N':
			switch( at(str,len,i+1) ){
			case 'O':
				if( at(str,len,i+2) == 'T' ){
					res = Tok_NOT; i += 3;
				}
				break;
			case 'U':
				if( at(str,len,i+2) == 'M' ){
					if( at(str,len,i+3) == 'B' ){
						if( at(str,len,i+4) == 'E' ){
							if( at(str,len,i+5) == 'R' ){
								res = Tok_NUMBER; i += 6;
							}
						}
					}
				}
				break;
			case 'V':
				if( at(str,len,i+2) == 'L' ){
					res = Tok_NVL; i += 3;
				}
				break;
			}
			break;
		case 'O':
			switch( at(str,len,i+1) ){
			case 'D':
				if( at(str,len,i+2) == 'D' ){
					res = Tok_ODD; i += 3;
				}
				break;
			case 'F':
				res = Tok_OF; i += 2;
				break;
			case 'N':
				if( at(str,len,i+2) == 'E' ){
					if( at(str,len,i+3) == 'O' ){
						if( at(str,len,i+4) == 'F' ){
							res = Tok_ONEOF; i += 5;
						}
					}
				}
				break;
			case 'P':
				if( at(str,len,i+2) == 'T' ){
					if( at(str,len,i+3) == 'I' ){
						if( at(str,len,i+4) == 'O' ){
							if( at(str,len,i+5) == 'N' ){
								if( at(str,len,i+6) == 'A' ){
									if( at(str,len,i+7) == 'L' ){
										res = Tok_OPTIONAL; i += 8;
									}
								}
							}
						}
					}
				}
				break;
			case 'R':
				res = Tok_OR; i += 2;
				break;
			case 'T':
				if( at(str,len,i+2) == 'H' ){
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'R' ){
							if( at(str,len,i+5) == 'W' ){
								if( at(str,len,i+6) == 'I' ){
									if( at(str,len,i+7) == 'S' ){
										if( at(str,len,i+8) == 'E' ){
											res = Tok_OTHERWISE; i += 9;
										}
									}
								}
							}
						}
					}
				}
				break;
			}
			break;
		case 'P':
			switch( at(str,len,i+1) ){
			case 'I':
				res = Tok_PI; i += 2;
				break;
			case 'R':
				if( at(str,len,i+2) == 'O' ){
					if( at(str,len,i+3) == 'C' ){
						if( at(str,len,i+4) == 'E' ){
							if( at(str,len,i+5) == 'D' ){
								if( at(str,len,i+6) == 'U' ){
									if( at(str,len,i+7) == 'R' ){
										if( at(str,len,i+8) == 'E' ){
											res = Tok_PROCEDURE; i += 9;
										}
									}
								}
							}
						}
					}
				}
				break;
			}
			break;
		case 'Q':
			if( at(str,len,i+1) == 'U' ){
				if( at(str,len,i+2) == 'E' ){
					if( at(str,len,i+3) == 'R' ){
						if( at(str,len,i+4) == 'Y' ){
							res = Tok_QUERY; i += 5;
						}
					}
				}
			}
			break;
		case 'R':
			switch( at(str,len,i+1) ){
			case 'E':
				switch( at(str,len,i+2) ){
				case 'A':
					if( at(str,len,i+3) == 'L' ){
						res = Tok_REAL; i += 4;
					}
					break;
				case 'F':
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'R' ){
							if( at(str,len,i+5) == 'E' ){
								if( at(str,len,i+6) == 'N' ){
									if( at(str,len,i+7) == 'C' ){
										if( at(str,len,i+8) == 'E' ){
											res = Tok_REFERENCE; i += 9;
										}
									}
								}
							}
						}
					}
					break;
				case 'M':
					if( at(str,len,i+3) == 'O' ){
						if( at(str,len,i+4) == 'V' ){
							if( at(str,len,i+5) == 'E' ){
								res = Tok_REMOVE; i += 6;
							}
						}
					}
					break;
				case 'N':
					if( at(str,len,i+3) == 'A' ){
						if( at(str,len,i+4) == 'M' ){
							if( at(str,len,i+5) == 'E' ){
								if( at(str,len,i+6) == 'D' ){
									res = Tok_RENAMED; i += 7;
								}
							}
						}
					}
					break;
				case 'P':
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'A' ){
							if( at(str,len,i+5) == 'T' ){
								res = Tok_REPEAT; i += 6;
							}
						}
					}
					break;
				case 'T':
					if( at(str,len,i+3) == 'U' ){
						if( at(str,len,i+4) == 'R' ){
							if( at(str,len,i+5) == 'N' ){
								res = Tok_RETURN; i += 6;
							}
						}
					}
					break;
				}
				break;
			case 'O':
				if( at(str,len,i+2) == 'L' ){
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'S' ){
							if( at(str,len,i+5) == 'O' ){
								if( at(str,len,i+6) == 'F' ){
									res = Tok_ROLESOF; i += 7;
								}
							}
						}
					}
				}
				break;
			case 'U':
				if( at(str,len,i+2) == 'L' ){
					if( at(str,len,i+3) == 'E' ){
						res = Tok_RULE; i += 4;
					}
				}
				break;
			}
			break;
		case 'S':
			switch( at(str,len,i+1) ){
			case 'C':
				if( at(str,len,i+2) == 'H' ){
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'M' ){
							if( at(str,len,i+5) == 'A' ){
								res = Tok_SCHEMA; i += 6;
							}
						}
					}
				}
				break;
			case 'E':
				switch( at(str,len,i+2) ){
				case 'L':
					switch( at(str,len,i+3) ){
					case 'E':
						if( at(str,len,i+4) == 'C' ){
							if( at(str,len,i+5) == 'T' ){
								res = Tok_SELECT; i += 6;
							}
						}
						break;
					case 'F':
						res = Tok_SELF; i += 4;
						break;
					}
					break;
				case 'T':
					res = Tok_SET; i += 3;
					break;
				}
				break;
			case 'I':
				switch( at(str,len,i+2) ){
				case 'N':
					res = Tok_SIN; i += 3;
					break;
				case 'Z':
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'O' ){
							if( at(str,len,i+5) == 'F' ){
								res = Tok_SIZEOF; i += 6;
							}
						}
					}
					break;
				}
				break;
			case 'K':
				if( at(str,len,i+2) == 'I' ){
					if( at(str,len,i+3) == 'P' ){
						res = Tok_SKIP; i += 4;
					}
				}
				break;
			case 'Q':
				if( at(str,len,i+2) == 'R' ){
					if( at(str,len,i+3) == 'T' ){
						res = Tok_SQRT; i += 4;
					}
				}
				break;
			case 'T':
				if( at(str,len,i+2) == 'R' ){
					if( at(str,len,i+3) == 'I' ){
						if( at(str,len,i+4) == 'N' ){
							if( at(str,len,i+5) == 'G' ){
								res = Tok_STRING; i += 6;
							}
						}
					}
				}
				break;
			case 'U':
				switch( at(str,len,i+2) ){
				case 'B':
					if( at(str,len,i+3) == 'T' ){
						if( at(str,len,i+4) == 'Y' ){
							if( at(str,len,i+5) == 'P' ){
								if( at(str,len,i+6) == 'E' ){
									if( at(str,len,i+7) == '_' ){
										if( at(str,len,i+8) == 'C' ){
											if( at(str,len,i+9) == 'O' ){
												if( at(str,len,i+10) == 'N' ){
													if( at(str,len,i+11) == 'S' ){
														if( at(str,len,i+12) == 'T' ){
															if( at(str,len,i+13) == 'R' ){
																if( at(str,len,i+14) == 'A' ){
																	if( at(str,len,i+15) == 'I' ){
																		if( at(str,len,i+16) == 'N' ){
																			if( at(str,len,i+17) == 'T' ){
																				res = Tok_SUBTYPE_CONSTRAINT; i += 18;
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									} else {
										res = Tok_SUBTYPE; i += 7;
									}
								}
							}
						}
					}
					break;
				case 'P':
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'R' ){
							if( at(str,len,i+5) == 'T' ){
								if( at(str,len,i+6) == 'Y' ){
									if( at(str,len,i+7) == 'P' ){
										if( at(str,len,i+8) == 'E' ){
											res = Tok_SUPERTYPE; i += 9;
										}
									}
								}
							}
						}
					}
					break;
				}
				break;
			}
			break;
		case 'T':
			switch( at(str,len,i+1) ){
			case 'A':
				if( at(str,len,i+2) == 'N' ){
					res = Tok_TAN; i += 3;
				}
				break;
			case 'H':
				if( at(str,len,i+2) == 'E' ){
					if( at(str,len,i+3) == 'N' ){
						res = Tok_THEN; i += 4;
					}
				}
				break;
			case 'O':
				if( at(str,len,i+2) == 'T' ){
					if( at(str,len,i+3) == 'A' ){
						if( at(str,len,i+4) == 'L' ){
							if( at(str,len,i+5) == '_' ){
								if( at(str,len,i+6) == 'O' ){
									if( at(str,len,i+7) == 'V' ){
										if( at(str,len,i+8) == 'E' ){
											if( at(str,len,i+9) == 'R' ){
												res = Tok_TOTAL_OVER; i += 10;
											}
										}
									}
								}
							}
						}
					}
				} else {
					res = Tok_TO; i += 2;
				}
				break;
			case 'R':
				if( at(str,len,i+2) == 'U' ){
					if( at(str,len,i+3) == 'E' ){
						res = Tok_TRUE; i += 4;
					}
				}
				break;
			case 'Y':
				if( at(str,len,i+2) == 'P' ){
					if( at(str,len,i+3) == 'E' ){
						if( at(str,len,i+4) == 'O' ){
							if( at(str,len,i+5) == 'F' ){
								res = Tok_TYPEOF; i += 6;
							}
						} else {
							res = Tok_TYPE; i += 4;
						}
					}
				}
				break;
			}
			break;
		case 'U':
			switch( at(str,len,i+1) ){
			case 'N':
				switch( at(str,len,i+2) ){
				case 'I':
					if( at(str,len,i+3) == 'Q' ){
						if( at(str,len,i+4) == 'U' ){
							if( at(str,len,i+5) == 'E' ){
								res = Tok_UNIQUE; i += 6;
							}
						}
					}
					break;
				case 'K':
					if( at(str,len,i+3) == 'N' ){
						if( at(str,len,i+4) == 'O' ){
							if( at(str,len,i+5) == 'W' ){
								if( at(str,len,i+6) == 'N' ){
									res = Tok_UNKNOWN; i += 7;
								}
							}
						}
					}
					break;
				case 'T':
					if( at(str,len,i+3) == 'I' ){
						if( at(str,len,i+4) == 'L' ){
							res = Tok_UNTIL; i += 5;
						}
					}
					break;
				}
				break;
			case 'S':
				if( at(str,len,i+2) == 'E' ){
					if( at(str,len,i+3) == 'D' ){
						if( at(str,len,i+4) == 'I' ){
							if( at(str,len,i+5) == 'N' ){
								res = Tok_USEDIN; i += 6;
							}
						}
					} else {
						res = Tok_USE; i += 3;
					}
				}
				break;
			}
			break;
		case 'V':
			if( at(str,len,i+1) == 'A' ){
				switch( at(str,len,i+2) ){
				case 'L':
					if( at(str,len,i+3) == 'U' ){
						if( at(str,len,i+4) == 'E' ){
							if( at(str,len,i+5) == '_' ){
								switch( at(str,len,i+6) ){
								case 'I':
									if( at(str,len,i+7) == 'N' ){
										res = Tok_VALUE_IN; i += 8;
									}
									break;
								case 'U':
									if( at(str,len,i+7) == 'N' ){
										if( at(str,len,i+8) == 'I' ){
											if( at(str,len,i+9) == 'Q' ){
												if( at(str,len,i+10) == 'U' ){
													if( at(str,len,i+11) == 'E' ){
														res = Tok_VALUE_UNIQUE; i += 12;
													}
												}
											}
										}
									}
									break;
								}
							} else {
								res = Tok_VALUE; i += 5;
							}
						}
					}
					break;
				case 'R':
					res = Tok_VAR; i += 3;
					break;
				}
			}
			break;
		case 'W':
			switch( at(str,len,i+1) ){
			case 'H':
				switch( at(str,len,i+2) ){
				case 'E':
					if( at(str,len,i+3) == 'R' ){
						if( at(str,len,i+4) == 'E' ){
							res = Tok_WHERE; i += 5;
						}
					}
					break;
				case 'I':
					if( at(str,len,i+3) == 'L' ){
						if( at(str,len,i+4) == 'E' ){
							res = Tok_WHILE; i += 5;
						}
					}
					break;
				}
				break;
			case 'I':
				if( at(str,len,i+2) == 'T' ){
					if( at(str,len,i+3) == 'H' ){
						res = Tok_WITH; i += 4;
					}
				}
				break;
			}
			break;
		case 'X':
			if( at(str,len,i+1) == 'O' ){
				if( at(str,len,i+2) == 'R' ){
					res = Tok_XOR; i += 3;
				}
			}
			break;
		case '[':
			res = Tok_Lbrack; i += 1;
			break;
		case '\\':
			res = Tok_Bslash; i += 1;
			break;
		case ']':
			res = Tok_Rbrack; i += 1;
			break;
		case '{':
			res = Tok_Lbrace; i += 1;
			break;
		case '|':
			if( at(str,len,i+1) == '|' ){
				res = Tok_2Bar; i += 2;
			} else {
				res = Tok_Bar; i += 1;
			}
			break;
		case '}':
			res = Tok_Rbrace; i += 1;
			break;
		}
		if(pos) *pos = i;
		return res;
	}
}
